"""LLM provider registry models and capability resolution helpers."""

from __future__ import annotations

from .llm_registry_catalog import build_provider_catalog
from .llm_registry_defaults import build_runtime_llm_defaults
from .llm_registry_loading import load_llm_provider_registry
from .llm_registry_model_resolution import (
    _apply_capability_overrides,
    _apply_limit_overrides,
    _default_chat_modalities,
    _default_embedding_modalities,
    _default_image_generation_modalities,
    _resolve_chat_model,
    _resolve_embedding_model,
    _resolve_image_generation_model,
    find_chat_model_meta,
    find_embedding_model_meta,
    find_image_generation_model_meta,
    find_provider_meta,
    find_provider_plan,
    resolve_embedding_dimension,
    resolve_provider_plan_meta,
    resolve_provider_model_catalog,
)
from .llm_registry_profile import resolve_llm_profile
from .models import (
    LLMCapabilitiesSettings,
    LLMCapabilityOverridesSettings,
    LLMLimitsOverrideSettings,
    LLMLimitsSettings,
    LLMModelCostModel,
    LLMModelMetadataOverrideSettings,
    LLMProviderSettings,
    LLMSelectionSettings,
)
from .llm_registry_models import (
    LLMAudioGenerationModelMetaModel,
    LLMChatCapabilitiesModel,
    LLMCustomProviderMetaModel,
    LLMEmbeddingModelMetaModel,
    LLMImageGenerationModelMetaModel,
    LLMModelMetaModel,
    LLMProviderCatalogEntryModel,
    LLMProviderFieldModel,
    LLMProviderMetaModel,
    LLMProviderPlanModel,
    LLMProviderRegistryModel,
    LLMResolvedEmbeddingModelMetaModel,
    LLMResolvedImageGenerationModelMetaModel,
    LLMResolvedModelMetaModel,
    LLMResolvedProviderCatalogModel,
    ResolvedLLMProfile,
)

__all__ = [
    "LLMAudioGenerationModelMetaModel",
    "LLMCapabilitiesSettings",
    "LLMCapabilityOverridesSettings",
    "LLMChatCapabilitiesModel",
    "LLMCustomProviderMetaModel",
    "LLMEmbeddingModelMetaModel",
    "LLMImageGenerationModelMetaModel",
    "LLMLimitsOverrideSettings",
    "LLMLimitsSettings",
    "LLMModelCostModel",
    "LLMModelMetaModel",
    "LLMModelMetadataOverrideSettings",
    "LLMProviderCatalogEntryModel",
    "LLMProviderFieldModel",
    "LLMProviderMetaModel",
    "LLMProviderPlanModel",
    "LLMProviderRegistryModel",
    "LLMProviderSettings",
    "LLMResolvedEmbeddingModelMetaModel",
    "LLMResolvedImageGenerationModelMetaModel",
    "LLMResolvedModelMetaModel",
    "LLMResolvedProviderCatalogModel",
    "LLMSelectionSettings",
    "ResolvedLLMProfile",
    "_apply_capability_overrides",
    "_apply_limit_overrides",
    "_default_chat_modalities",
    "_default_embedding_modalities",
    "_default_image_generation_modalities",
    "_resolve_chat_model",
    "_resolve_embedding_model",
    "_resolve_image_generation_model",
    "build_provider_catalog",
    "build_runtime_llm_defaults",
    "find_chat_model_meta",
    "find_embedding_model_meta",
    "find_image_generation_model_meta",
    "find_provider_meta",
    "find_provider_plan",
    "load_llm_provider_registry",
    "resolve_embedding_dimension",
    "resolve_llm_profile",
    "resolve_provider_plan_meta",
    "resolve_provider_model_catalog",
]
