"""Contracts for the asynchronous L2 cognition pipeline."""

from __future__ import annotations

import time as time

from .batch_models import (
    L2BatchEvent,
    L2BatchJob,
    L2EntityReconcileJob,
    L2EventWindow,
    L2EventWindowSummary,
    L2HistoryContext,
    L2PendingBatchBucket,
    L2SnapshotRefreshJob,
    ManualL2EventRequest,
    build_l2_batch_bucket_key,
)
from .candidate_models import (
    L2AssertionCandidate,
    L2CandidateSet,
    L2ConflictArbitrationResult,
    L2GraphCandidate,
    L2UnifiedExtractionResult,
)
from .entities.models import (
    L2BatchEntityResolutionItem,
    L2EntityCandidate,
    L2EntityResolution,
    L2EntityResolutionMention,
    L2ExistingRecord,
    L2FocalEntityRef,
    L2KnowledgeEdgeWrite,
    L2ReconcileAssertion,
    L2ReconcileEntity,
    L2ReconcileGraphFact,
    L2SourceEvent,
    L2TomAssertionWrite,
    ResolvedEntityMention,
)
from .episode_models import EpisodeCandidateJob, EpisodeConsolidationStats, EpisodeWrite
from .phase_models import (
    ContradictionHint,
    L2ClaimEvidenceMode,
    L2Phase1Entity,
    L2Phase1FactClaim,
    L2Phase1ResolvedRef,
    L2Phase1Result,
    L2Phase2AssertionCandidate,
    L2Phase2ClaimAssessment,
    L2Phase2Result,
    ReconciledTraitOutcome,
    StructuredEntityHint,
    StructuredGraphHint,
)


__all__ = [
    "build_l2_batch_bucket_key",
    "ContradictionHint",
    "EpisodeCandidateJob",
    "EpisodeConsolidationStats",
    "EpisodeWrite",
    "L2AssertionCandidate",
    "L2BatchEvent",
    "L2BatchEntityResolutionItem",
    "L2BatchJob",
    "L2CandidateSet",
    "L2ConflictArbitrationResult",
    "L2ClaimEvidenceMode",
    "L2EntityCandidate",
    "L2EntityResolution",
    "L2EntityResolutionMention",
    "L2EntityReconcileJob",
    "L2ExistingRecord",
    "L2ReconcileAssertion",
    "L2ReconcileEntity",
    "L2ReconcileGraphFact",
    "L2EventWindow",
    "L2EventWindowSummary",
    "L2FocalEntityRef",
    "L2GraphCandidate",
    "L2HistoryContext",
    "L2KnowledgeEdgeWrite",
    "L2PendingBatchBucket",
    "L2Phase1Entity",
    "L2Phase1FactClaim",
    "L2Phase1ResolvedRef",
    "L2Phase1Result",
    "L2Phase2AssertionCandidate",
    "L2Phase2ClaimAssessment",
    "L2Phase2Result",
    "L2SnapshotRefreshJob",
    "L2SourceEvent",
    "L2TomAssertionWrite",
    "L2UnifiedExtractionResult",
    "ManualL2EventRequest",
    "ReconciledTraitOutcome",
    "ResolvedEntityMention",
    "StructuredEntityHint",
    "StructuredGraphHint",
]
