"""Channel contracts - re-exported from magi-plugin-sdk."""

from magi_plugin_sdk.channels import (  # noqa: F401
    ChannelConfig,
    ChannelAttachmentStoreProtocol,
    ChannelControlCommandResult,
    ChannelControlPortProtocol,
    ChannelCursorClearProof,
    ChannelInboundClearStrategy,
    ChannelInboundClearRequest,
    ChannelInboundContext,
    ChannelInboundEvidence,
    ChannelInboundRejectedError,
    ChannelInboundRejectionReason,
    ChannelMessageDispatcherProtocol,
    ChannelMessageDispatchOutcome,
    ChannelProviderTimeEvidence,
    ChannelSessionMapping,
    ChannelTarget,
    InboundMessage,
    OutboundContent,
)

__all__ = [
    "ChannelConfig",
    "ChannelAttachmentStoreProtocol",
    "ChannelControlCommandResult",
    "ChannelControlPortProtocol",
    "ChannelCursorClearProof",
    "ChannelInboundClearStrategy",
    "ChannelInboundClearRequest",
    "ChannelInboundContext",
    "ChannelInboundEvidence",
    "ChannelInboundRejectedError",
    "ChannelInboundRejectionReason",
    "ChannelMessageDispatcherProtocol",
    "ChannelMessageDispatchOutcome",
    "ChannelProviderTimeEvidence",
    "ChannelSessionMapping",
    "ChannelTarget",
    "InboundMessage",
    "OutboundContent",
]
