[package]
name = "magi-server"
version = "0.1.29"
description = "Standalone Magi service"
edition = "2021"

[dependencies]
magi-platform = { path = "../crates/magi-platform" }
libc = "0.2"
magi-server-runtime = { path = "../crates/magi-server-runtime" }
magi-service-contract = { path = "../crates/magi-service-contract" }
serde_json = "1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
magi-gateway = { path = "../crates/magi-gateway" }
