"""Chat-owned orchestration planning and aggregation helpers."""
from __future__ import annotations

import json
import os
import re
from datetime import datetime, timedelta
from typing import Any, Optional

from ....core.logger import get_logger
from ....context.service import ContextAssemblyService
from ....context.scenarios import Scenario
from ....tools.registry import ToolRegistry
from ....tools.schema import ToolExecutionContext
from ...orchestration import PlannedSubtask, SubtaskPlan, TaskOrchestrationState
from ..common import OrchestrationPlan
from .prompt_service import ChatPromptService
from .session_service import ChatSessionService

logger = get_logger(__name__)

STRUCTURED_PLANNING_TIMEOUT_SECONDS = 180.0


class ChatPlanningService:
    """Owns parent-task planning and aggregation for generic chat orchestration."""

    def __init__(
        self,
        *,
        agent_id: str,
        runtime_key: str,
        context_service: ContextAssemblyService,
        prompt_service: ChatPromptService,
        session_service: ChatSessionService,
        tool_registry: ToolRegistry,
        parent_task_agent_type: str,
    ) -> None:
        self._agent_id = agent_id
        self._runtime_key = runtime_key
        self._context_service = context_service
        self._prompt_service = prompt_service
        self._session_service = session_service
        self._tool_registry = tool_registry
        self._parent_task_agent_type = parent_task_agent_type

    async def generate_subtask_plan(
        self,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan | dict[str, Any],
        user_id: str,
        session_id: str,
    ) -> SubtaskPlan:
        if isinstance(orchestration_plan, dict):
            orchestration_plan = OrchestrationPlan(
                mode=str(orchestration_plan.get("mode", "direct") or "direct"),
                planner=str(orchestration_plan.get("planner", "task_agent") or "task_agent"),
                default_leaf_type=str(orchestration_plan.get("default_leaf_type", "Explore") or "Explore"),
                allow_parallel=bool(orchestration_plan.get("allow_parallel", True)),
            )
        request_profile = self._classify_request_profile(
            user_message=user_message,
            default_leaf_type=orchestration_plan.default_leaf_type,
        )
        raw_plan: Optional[SubtaskPlan] = None
        if orchestration_plan.planner == "plan_worker":
            raw_plan = await self._plan_with_plan_worker(
                user_message=user_message,
                user_id=user_id,
                session_id=session_id,
            )
        if raw_plan is None:
            raw_plan = await self._plan_with_task_agent(
                user_message=user_message,
                history=history,
                orchestration_plan=orchestration_plan,
                request_profile=request_profile,
            )
        if raw_plan is None:
            raw_plan = SubtaskPlan(
                summary="Fallback decomposition generated by chat task agent.",
                subtasks=self._fallback_subtask_plan(
                    user_message=user_message,
                    default_leaf_type=orchestration_plan.default_leaf_type,
                    request_profile=request_profile,
                ),
            )
        return self._normalize_subtask_plan(
            user_message=user_message,
            raw_plan=raw_plan,
            default_leaf_type=orchestration_plan.default_leaf_type,
            request_profile=request_profile,
        )

    async def aggregate_orchestration(self, state: TaskOrchestrationState) -> str:
        payload = self._prompt_service.build_aggregation_payload(state)
        history = await self._session_service.get_or_load_history(state.user_id, state.session_id)
        filtered_history = self._prompt_service.filter_history_for_aggregation(history)
        system_prompt = await self._context_service.build_system_prompt(
            user_id=state.user_id,
            session_id=state.session_id,
            user_message=state.root_user_message,
            task_category="chat",
            scenario=Scenario.CHAT,
        )
        messages = filtered_history + [
            {
                "role": "user",
                "content": self._prompt_service.build_aggregation_user_message(state, payload),
            }
        ]
        try:
            response = await self._prompt_service.call_llm(
                system_prompt=system_prompt,
                messages=messages,
                disable_thinking=False,
            )
        except Exception as exc:
            logger.warning(
                "Parent aggregation LLM call failed | orchestration_id=%s error=%s",
                state.orchestration_id,
                exc,
            )
            response = ""
        if response.strip():
            return response.strip()
        logger.warning(
            "Parent aggregation returned empty response | orchestration_id=%s completed_subtasks=%s failed_subtasks=%s",
            state.orchestration_id,
            len(payload.get("completed_subtasks", [])),
            len(payload.get("failed_subtasks", [])),
        )
        return self._prompt_service.build_aggregation_fallback(state)

    async def _plan_with_task_agent(
        self,
        *,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan,
        request_profile: str,
    ) -> Optional[SubtaskPlan]:
        recent_history = [
            {
                "role": str(item.get("role", "unknown")),
                "content": str(item.get("content", ""))[:400],
            }
            for item in history[-4:]
            if isinstance(item, dict) and str(item.get("content", "")).strip()
        ]
        if request_profile == "research":
            seed_subtasks = [item.to_dict() for item in self._build_research_seed_subtasks(user_message)]
            planning_prompt = {
                "planning_profile": "research",
                "user_request": user_message,
                "recent_history": recent_history,
                "default_leaf_type": "general-purpose",
                "allow_parallel": orchestration_plan.allow_parallel,
                "date_range_hint": self._extract_date_range_hint(user_message),
                "seed_subtasks": seed_subtasks,
                "requirements": [
                    "Decompose into bounded, independent research subtasks that a generic worker can complete without reading sibling outputs.",
                    "Favor parallel subtasks that split by source family, verification responsibility, or retrieval angle.",
                    "Only include web-fetch when the user requests details, verification, full text, or when source summaries are likely insufficient.",
                    "Do not create a final synthesis worker that depends on sibling worker outputs; the parent task agent will aggregate.",
                    "Each research subtask should collect evidence that preserves title, date, source, link, and a short summary when available.",
                ],
            }
            system_prompt = (
                "You are a parent task agent planning bounded generic research subtasks. "
                "Return ONLY valid JSON with this schema: "
                '{"summary":"string","subtasks":[{"description":"string","subagent_type":"general-purpose","prompt":"string","parallel_group":"string"}]}. '
                "Produce execution-ready leaf tasks only. Do not answer the user request directly. "
                "Never emit a worker whose only job is final synthesis across sibling results."
            )
        else:
            planning_prompt = {
                "planning_profile": request_profile,
                "user_request": user_message,
                "recent_history": recent_history,
                "default_leaf_type": orchestration_plan.default_leaf_type,
                "allow_parallel": orchestration_plan.allow_parallel,
                "requirements": [
                    "Decompose into bounded leaf subtasks owned by the parent task agent.",
                    "Favor parallel subtasks when there are no strong dependencies.",
                    "For codebase architecture analysis, prefer separate subtasks for directory structure, tech stack, frontend, backend, and project progress when relevant.",
                ],
            }
            system_prompt = (
                "You are a parent task agent planning bounded leaf subtasks. "
                "Return ONLY valid JSON with this schema: "
                '{"summary":"string","subtasks":[{"description":"string","subagent_type":"Explore|general-purpose","prompt":"string","parallel_group":"string"}]}. '
                "Do not answer the user request directly. Produce execution-ready leaf tasks only."
            )
        try:
            response = await self._prompt_service.call_llm(
                system_prompt=system_prompt,
                messages=[{"role": "user", "content": json.dumps(planning_prompt, ensure_ascii=False)}],
                disable_thinking=False,
                json_mode=True,
                timeout_seconds=STRUCTURED_PLANNING_TIMEOUT_SECONDS,
            )
        except Exception as exc:
            logger.warning("Task-agent planning call failed | error=%s", exc)
            return None
        if not str(response or "").strip():
            logger.warning(
                "Task-agent planning returned empty response | user_id=%s request_preview=%s",
                self._agent_id,
                user_message[:120],
            )
            return None
        parsed_plan = self._parse_subtask_plan(response)
        if parsed_plan is None:
            logger.warning(
                "Task-agent planning returned non-executable plan | request_preview=%s response_preview=%s",
                user_message[:120],
                str(response).strip()[:300],
            )
        return parsed_plan

    async def _plan_with_plan_worker(
        self,
        *,
        user_message: str,
        user_id: str,
        session_id: str,
    ) -> Optional[SubtaskPlan]:
        context = self._build_agent_tool_context(user_id, session_id)
        result = await self._tool_registry.execute(
            "agent",
            {
                "action": "launch",
                "subagent_type": "Plan",
                "description": "plan leaf subtasks",
                "prompt": (
                    "Decompose the parent task into bounded leaf workers. "
                    "Return JSON with summary, findings, evidence, gaps, next_steps, and subtasks only. "
                    f"Parent task: {user_message}"
                ),
                "run_in_background": False,
                "target_task_agent_type": self._parent_task_agent_type,
                "target_task_agent_id": user_id,
                "parent_task_agent_type": self._parent_task_agent_type,
                "parent_task_agent_id": user_id,
            },
            context,
        )
        if not result.success or not isinstance(result.data, dict):
            return None
        payload = result.data.get("result")
        if not isinstance(payload, dict):
            return None
        subtasks = payload.get("subtasks")
        if not isinstance(subtasks, list) or not subtasks:
            return None
        return SubtaskPlan.from_dict(
            {
                "summary": str(payload.get("summary", "")).strip(),
                "subtasks": subtasks,
            }
        )

    def should_route_to_explore_task_agent(self, *, user_message: str, orchestration_plan: OrchestrationPlan) -> bool:
        if orchestration_plan.mode != "decompose":
            return False
        if orchestration_plan.default_leaf_type != "Explore":
            return False
        lowered = user_message.lower()
        return any(
            keyword in lowered
            for keyword in [
                "architecture",
                "codebase",
                "repo",
                "跨模块",
                "跨子系统",
                "代码架构",
                "项目架构",
                "代码库",
                "目录结构",
            ]
        )

    def _normalize_subtask_plan(
        self,
        *,
        user_message: str,
        raw_plan: SubtaskPlan,
        default_leaf_type: str,
        request_profile: str,
    ) -> SubtaskPlan:
        raw_subtasks = list(raw_plan.subtasks)
        if not raw_subtasks:
            raw_subtasks = self._fallback_subtask_plan(
                user_message,
                default_leaf_type,
                request_profile=request_profile,
            )
        normalized_subtasks: list[PlannedSubtask] = []
        for item in raw_subtasks:
            description = item.description
            subtask_prompt = item.prompt
            subagent_type = str(item.subagent_type or default_leaf_type).strip()
            if subagent_type not in {"Explore", "general-purpose"}:
                subagent_type = default_leaf_type if default_leaf_type in {"Explore", "general-purpose"} else "Explore"
            if request_profile == "research":
                subagent_type = "general-purpose"
            normalized_subtasks.append(
                PlannedSubtask(
                    description=description,
                    subagent_type=subagent_type,
                    prompt=self._build_leaf_worker_prompt(
                        root_user_message=user_message,
                        subtask_description=description,
                        subtask_prompt=subtask_prompt,
                        request_profile=request_profile,
                    ),
                    parallel_group=item.parallel_group,
                )
            )
        return SubtaskPlan(
            summary=raw_plan.summary,
            subtasks=normalized_subtasks,
        )

    def _parse_subtask_plan(self, response: str) -> Optional[SubtaskPlan]:
        raw = str(response or "").strip()
        if not raw:
            return None
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError:
            return None
        if not isinstance(payload, dict):
            return None
        subtasks = payload.get("subtasks")
        if not isinstance(subtasks, list) or not subtasks:
            return None
        normalized = SubtaskPlan.from_dict(payload)
        if not normalized.subtasks:
            return None
        return normalized

    def _fallback_subtask_plan(
        self,
        user_message: str,
        default_leaf_type: str,
        *,
        request_profile: str,
    ) -> list[PlannedSubtask]:
        is_repo_architecture = any(
            keyword in user_message.lower()
            for keyword in ["architecture", "codebase", "repo", "代码架构", "项目架构", "代码库", "目录结构"]
        )
        leaf_type = default_leaf_type if default_leaf_type in {"Explore", "general-purpose"} else "Explore"
        if request_profile == "research":
            return self._build_research_seed_subtasks(user_message)
        if is_repo_architecture:
            return [
                PlannedSubtask(
                    description="Map repository layout",
                    subagent_type="Explore",
                    prompt="Analyze the top-level directory structure, major modules, and entry folders.",
                    parallel_group="group_a",
                ),
                PlannedSubtask(
                    description="Identify technology stack",
                    subagent_type="Explore",
                    prompt="Inspect dependency manifests and boot files to identify the backend, frontend, storage, and runtime stack.",
                    parallel_group="group_a",
                ),
                PlannedSubtask(
                    description="Analyze frontend structure",
                    subagent_type="Explore",
                    prompt="Focus on frontend organization, bootstrap flow, routing, and the main UI entry points.",
                    parallel_group="group_a",
                ),
                PlannedSubtask(
                    description="Analyze backend modules",
                    subagent_type="Explore",
                    prompt="Focus on backend module boundaries, runtime startup, task agent chain, and the main execution flow.",
                    parallel_group="group_a",
                ),
                PlannedSubtask(
                    description="Inspect project progress",
                    subagent_type="Explore",
                    prompt="Look for docs, progress trackers, release notes, or TODO-style files that indicate the current project status and recent progress.",
                    parallel_group="group_a",
                ),
            ]
        return [
            PlannedSubtask(
                description="Gather primary context",
                subagent_type=leaf_type,
                prompt="Collect the most relevant files, modules, and source-of-truth evidence for the request.",
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Analyze implementation details",
                subagent_type=leaf_type,
                prompt="Inspect the core implementation path, dependencies, and behavior that matter for the request.",
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Summarize risks and gaps",
                subagent_type=leaf_type,
                prompt="Identify open questions, gaps, and next actions needed to complete the request.",
                parallel_group="group_b",
            ),
        ]

    def _build_leaf_worker_prompt(
        self,
        *,
        root_user_message: str,
        subtask_description: str,
        subtask_prompt: str,
        request_profile: str,
    ) -> str:
        if request_profile == "research":
            date_range_hint = self._extract_date_range_hint(root_user_message)
            lines = [
                f"Parent user request: {root_user_message}",
                f"Assigned subtask: {subtask_description}",
                "Task-specific instructions:",
                subtask_prompt,
                "Success criteria:",
                "- Stay strictly within this subtask scope.",
                "- Prefer web-search for discovery and only use web-fetch when the task explicitly requires article details or verification.",
                "- When a normalized date range is available, pass it to web-search via `start_date` and `end_date` instead of relying on a fuzzy year in the query.",
                "- Preserve concrete evidence for each usable result: title, date, source, canonical link, and a short summary when available.",
                "- In findings, use `title` for the headline, `detail` for `DATE | SOURCE | SUMMARY`, and `path` for the canonical article URL.",
                "- If the available evidence is thin or conflicting, record it in gaps instead of guessing.",
                "- Do not fabricate publication dates, links, or sources.",
            ]
            if date_range_hint:
                lines.insert(
                    4,
                    f"Normalized date range: {date_range_hint['start_date']} to {date_range_hint['end_date']} (inclusive).",
                )
            return "\n".join(lines)
        return "\n".join(
            [
                f"Parent user request: {root_user_message}",
                f"Assigned subtask: {subtask_description}",
                "Task-specific instructions:",
                subtask_prompt,
                "Success criteria:",
                "- Stay strictly within this subtask scope.",
                "- Use absolute file paths in findings and evidence when you reference code.",
                "- Prefer validated findings over speculation.",
                "- If information is missing, put it into gaps instead of guessing.",
                "- Do not duplicate likely sibling subtasks unless it is necessary evidence.",
            ]
        )

    def _classify_request_profile(self, *, user_message: str, default_leaf_type: str) -> str:
        lowered = user_message.lower()
        if default_leaf_type == "Explore" and any(
            keyword in lowered
            for keyword in ["architecture", "codebase", "repo", "代码架构", "项目架构", "代码库", "目录结构"]
        ):
            return "repo_architecture"
        if self._is_complex_research_request(user_message):
            return "research"
        return "generic"

    def _is_complex_research_request(self, user_message: str) -> bool:
        lowered = user_message.lower()
        has_information_domain = any(
            keyword in lowered
            for keyword in [
                "news",
                "新闻",
                "头条",
                "消息",
                "最近",
                "过去",
                "近",
                "本月",
                "资料",
                "信息",
                "来源",
                "链接",
                "source",
                "link",
                "核实",
                "verify",
                "compare",
                "对比",
                "汇总",
            ]
        )
        has_complex_constraint = any(
            keyword in lowered
            for keyword in [
                "最近7天",
                "最近 7 天",
                "近7天",
                "过去7天",
                "最近一周",
                "近一周",
                "本月",
                "这个月",
                "给我",
                "条",
                "top",
                "链接",
                "来源",
                "详情",
                "展开",
                "核实",
                "verify",
                "交叉验证",
                "重要的",
            ]
        )
        return has_information_domain and has_complex_constraint

    def _needs_research_fetch(self, user_message: str) -> bool:
        lowered = user_message.lower()
        return any(
            keyword in lowered
            for keyword in ["详情", "展开", "全文", "原文", "核实", "verify", "交叉验证", "具体看", "深挖"]
        )

    def _build_research_seed_subtasks(self, user_message: str) -> list[PlannedSubtask]:
        date_range_hint = self._extract_date_range_hint(user_message)
        date_suffix = ""
        if date_range_hint:
            date_suffix = (
                f" Keep the work inside {date_range_hint['start_date']} to {date_range_hint['end_date']} (inclusive)."
            )
        subtasks = [
            PlannedSubtask(
                description="Search official and local-source coverage",
                subagent_type="general-purpose",
                prompt=(
                    "Search official, government, and local-source coverage that matches the user's request."
                    " Collect the strongest candidate items with title, date, source, link, and a short summary."
                    f"{date_suffix}"
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Search major media and commercial-source coverage",
                subagent_type="general-purpose",
                prompt=(
                    "Search major media, commercial, or independent sources that match the user's request."
                    " Collect the strongest candidate items with title, date, source, link, and a short summary."
                    f"{date_suffix}"
                ),
                parallel_group="group_a",
            ),
        ]
        if self._needs_research_fetch(user_message):
            subtasks.append(
                PlannedSubtask(
                    description="Fetch and verify article details",
                    subagent_type="general-purpose",
                    prompt=(
                        "For the most important candidate items, fetch article pages as needed to verify dates,"
                        " titles, links, and summaries before the parent task aggregates the answer."
                        f"{date_suffix}"
                    ),
                    parallel_group="group_b",
                )
            )
        return subtasks

    def _extract_date_range_hint(self, user_message: str) -> Optional[dict[str, str]]:
        lowered = user_message.lower()
        today = datetime.now().date()

        relative_days_match = re.search(r"(最近|过去|近)\s*(\d+)\s*天", user_message)
        if relative_days_match:
            days = max(1, int(relative_days_match.group(2)))
            start_date = today - timedelta(days=days - 1)
            return {"start_date": start_date.isoformat(), "end_date": today.isoformat()}

        if any(token in lowered for token in ["最近一周", "近一周", "过去一周", "last week"]):
            start_date = today - timedelta(days=6)
            return {"start_date": start_date.isoformat(), "end_date": today.isoformat()}

        if any(token in lowered for token in ["本月", "这个月", "this month"]):
            start_date = today.replace(day=1)
            return {"start_date": start_date.isoformat(), "end_date": today.isoformat()}

        if any(token in lowered for token in ["本周", "这周", "this week"]):
            start_date = today - timedelta(days=today.weekday())
            return {"start_date": start_date.isoformat(), "end_date": today.isoformat()}

        return None

    def _build_agent_tool_context(self, user_id: str, session_id: str) -> ToolExecutionContext:
        return ToolExecutionContext(
            agent_id=self._runtime_key,
            workspace=os.getcwd(),
            env_vars={
                "user_id": user_id,
                "session_id": session_id,
                "target_task_agent_type": self._parent_task_agent_type,
                "target_task_agent_id": user_id,
                "parent_task_agent_type": self._parent_task_agent_type,
                "parent_task_agent_id": user_id,
            },
            permissions=["authenticated"],
        )
