"""Chat-owned orchestration planning and aggregation helpers."""
from __future__ import annotations

import json
from typing import Any, Optional

from ....core.logger import get_logger
from ....context.service import ContextAssemblyService
from ....context.scenarios import Scenario
from ....events.domain_payloads import TaskContext
from ....i18n import llm_language_label
from ....llm.streaming_events import get_stream_sink, stream_source
from ....tools.registry import ToolRegistry
from ....tools.tool_hint_resolver import ToolHintResolver
from ...execution.tool_invocation_service import (
    InvocationContext,
    ToolCall as _ServiceToolCall,
)
from ...orchestration import PlannedSubtask, SubtaskPlan, TaskOrchestrationState
from ..common import OrchestrationPlan
from .history_service import ChatHistoryService
from .planning_prompts import ChatPlanningPromptMixin
from .prompt_service import ChatPromptService

logger = get_logger(__name__)

STRUCTURED_PLANNING_TIMEOUT_SECONDS = 180.0


class ChatPlanningService(ChatPlanningPromptMixin):
    """Owns parent-task planning and aggregation for generic chat orchestration."""

    _FILE_TOOL_HINT_CANDIDATES = ["glob", "grep", "file_read"]
    _WEB_TOOL_HINT_CANDIDATES = ["web-search", "web-fetch"]

    def __init__(
        self,
        *,
        agent_id: str,
        runtime_key: str,
        context_service: ContextAssemblyService,
        prompt_service: ChatPromptService,
        history_service: ChatHistoryService,
        tool_registry: ToolRegistry,
        parent_task_agent_type: str,
        tool_hint_resolver: ToolHintResolver | None = None,
    ) -> None:
        self._agent_id = agent_id
        self._runtime_key = runtime_key
        self._context_service = context_service
        self._prompt_service = prompt_service
        self._history_service = history_service
        self._tool_registry = tool_registry
        self._parent_task_agent_type = parent_task_agent_type
        self._tool_hint_resolver = tool_hint_resolver or ToolHintResolver(tool_registry)

    @property
    def _tool_invocation_service(self):
        from ...execution.tool_invocation_service import get_tool_invocation_service
        if not hasattr(self, "_tool_invocation_service_cached"):
            self._tool_invocation_service_cached = get_tool_invocation_service(self._tool_registry)
        return self._tool_invocation_service_cached

    async def generate_subtask_plan(
        self,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan | dict[str, Any],
        user_id: str,
        session_id: str,
        run_id: str | None = None,
        run_revision: int = 0,
        workspace_root: str | None = None,
    ) -> SubtaskPlan:
        if isinstance(orchestration_plan, dict):
            orchestration_plan = OrchestrationPlan(
                mode=str(orchestration_plan.get("mode", "direct") or "direct"),
                planner=str(orchestration_plan.get("planner", "task_agent") or "task_agent"),
                default_leaf_type=str(orchestration_plan.get("default_leaf_type", "CodeExplore") or "CodeExplore"),
                allow_parallel=bool(orchestration_plan.get("allow_parallel", True)),
            )
        request_profile = self._classify_request_profile(
            user_message=user_message,
            default_leaf_type=orchestration_plan.default_leaf_type,
        )
        raw_plan: Optional[SubtaskPlan] = None
        if orchestration_plan.planner == "plan_worker":
            raw_plan = await self._plan_with_plan_worker(
                user_message=user_message,
                user_id=user_id,
                session_id=session_id,
                run_id=run_id,
                run_revision=run_revision,
                workspace_root=workspace_root,
            )
        if raw_plan is None:
            raw_plan = await self._plan_with_task_agent(
                user_message=user_message,
                history=history,
                orchestration_plan=orchestration_plan,
                request_profile=request_profile,
                workspace_root=workspace_root,
            )
        if raw_plan is None:
            raw_plan = SubtaskPlan(
                summary="Fallback decomposition generated by chat task agent.",
                subtasks=self._fallback_subtask_plan(
                    user_message=user_message,
                    default_leaf_type=orchestration_plan.default_leaf_type,
                    request_profile=request_profile,
                ),
            )
        return self._normalize_subtask_plan(
            user_message=user_message,
            raw_plan=raw_plan,
            default_leaf_type=orchestration_plan.default_leaf_type,
            request_profile=request_profile,
        )

    async def aggregate_orchestration(self, state: TaskOrchestrationState) -> str:
        state.metadata["aggregation_streamed"] = False
        payload = self._prompt_service.build_aggregation_payload(state)
        history = await self._history_service.get_or_load_history(state.user_id, state.session_id)
        filtered_history = self._prompt_service.filter_history_for_aggregation(history)
        system_prompt = await self._context_service.build_system_prompt(
            user_id=state.user_id,
            session_id=state.session_id,
            user_message=state.root_user_message,
            task_category="analysis",
            scenario=Scenario.ANALYSIS,
            include_tool_catalog=False,
            persona_id=str(state.metadata.get("persona_id") or "").strip() or None,
        )
        if self._prompt_service.should_use_failure_status_path(payload):
            return await self._render_failure_status(
                state=state,
                payload=payload,
                base_system_prompt=system_prompt,
                filtered_history=filtered_history,
            )
        system_prompt = self._prompt_service.build_aggregation_system_prompt(
            base_system_prompt=system_prompt,
            state=state,
            payload=payload,
        )
        messages = self._prompt_service.build_aggregation_messages(
            history_messages=filtered_history,
            state=state,
            payload=payload,
        )
        try:
            if get_stream_sink() is not None:
                chunks: list[str] = []
                async with stream_source("aggregator"):
                    async for event in self._prompt_service.call_llm_stream(
                        system_prompt=system_prompt,
                        messages=messages,
                        disable_thinking=False,
                        event_context={
                            "request_kind": "task_agent:aggregator",
                            "agent_id": self._agent_id,
                            "session_id": state.session_id,
                        },
                    ):
                        if event.kind == "text_delta" and event.text:
                            chunks.append(event.text)
                response = "".join(chunks)
                state.metadata["aggregation_streamed"] = bool(response.strip())
            else:
                response = await self._prompt_service.call_llm(
                    system_prompt=system_prompt,
                    messages=messages,
                    disable_thinking=False,
                    event_context={
                        "request_kind": "task_agent:aggregator",
                        "agent_id": self._agent_id,
                        "session_id": state.session_id,
                    },
                )
        except Exception as exc:
            logger.warning(
                "Parent aggregation LLM call failed | orchestration_id=%s error=%s",
                state.orchestration_id,
                exc,
            )
            response = ""
        if response.strip():
            return response.strip()
        state.metadata["aggregation_streamed"] = False
        logger.warning(
            "Parent aggregation returned empty response | orchestration_id=%s completed_subtasks=%s failed_subtasks=%s",
            state.orchestration_id,
            len(payload.get("completed_subtasks", [])),
            len(payload.get("failed_subtasks", [])),
        )
        return self._prompt_service.build_aggregation_fallback(state)

    async def _render_failure_status(
        self,
        *,
        state: TaskOrchestrationState,
        payload: dict[str, Any],
        base_system_prompt: str,
        filtered_history: list[dict[str, str]],
    ) -> str:
        system_prompt = self._prompt_service.build_failure_status_system_prompt(
            base_system_prompt=base_system_prompt,
            state=state,
        )
        messages = self._prompt_service.build_failure_status_messages(
            history_messages=filtered_history,
            state=state,
            payload=payload,
        )
        try:
            if get_stream_sink() is not None:
                chunks: list[str] = []
                async with stream_source("failure_status"):
                    async for event in self._prompt_service.call_llm_stream(
                        system_prompt=system_prompt,
                        messages=messages,
                        disable_thinking=True,
                        event_context={
                            "request_kind": "task_agent:failure_status",
                            "agent_id": self._agent_id,
                            "session_id": state.session_id,
                        },
                    ):
                        if event.kind == "text_delta" and event.text:
                            chunks.append(event.text)
                response = "".join(chunks)
                state.metadata["aggregation_streamed"] = bool(response.strip())
            else:
                response = await self._prompt_service.call_llm(
                    system_prompt=system_prompt,
                    messages=messages,
                    disable_thinking=True,
                    event_context={
                        "request_kind": "task_agent:failure_status",
                        "agent_id": self._agent_id,
                        "session_id": state.session_id,
                    },
                )
        except Exception as exc:
            logger.warning(
                "Parent failure-status LLM call failed | orchestration_id=%s error=%s",
                state.orchestration_id,
                exc,
            )
            response = ""
        if response.strip():
            return response.strip()
        state.metadata["aggregation_streamed"] = False
        logger.warning(
            "Parent failure-status returned empty response | orchestration_id=%s failed_subtasks=%s",
            state.orchestration_id,
            len(payload.get("failed_subtasks", [])),
        )
        return self._prompt_service.build_failure_status_fallback(state, payload)

    async def _plan_with_task_agent(
        self,
        *,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan,
        request_profile: str,
        workspace_root: str | None = None,
    ) -> Optional[SubtaskPlan]:
        recent_history = [
            {
                "role": str(item.get("role", "unknown")),
                "content": str(item.get("content", ""))[:400],
            }
            for item in history[-4:]
            if isinstance(item, dict) and str(item.get("content", "")).strip()
        ]
        if request_profile == "research":
            target_language = llm_language_label()
            seed_subtasks = [item.to_dict() for item in self._build_research_seed_subtasks(user_message)]
            task_hint = self._resolve_planning_task_hint(
                user_message=user_message,
                request_profile=request_profile,
                default_leaf_type="general-purpose",
            )
            planning_prompt = {
                "planning_profile": "research",
                "target_language": target_language,
                "user_request": user_message,
                "recent_history": recent_history,
                "default_leaf_type": "general-purpose",
                "allow_parallel": orchestration_plan.allow_parallel,
                "date_range_hint": self._extract_date_range_hint(user_message),
                "task_hints": task_hint,
                "seed_subtasks": seed_subtasks,
                "requirements": [
                    "Decompose into bounded, independent research subtasks that a generic worker can complete without reading sibling outputs.",
                    "Favor parallel subtasks that split by source family, verification responsibility, or retrieval angle.",
                    "Only include web-fetch when the user requests details, verification, full text, or when source summaries are likely insufficient.",
                    "The parent task agent owns cross-source synthesis. Do not create a final synthesis worker that depends on sibling worker outputs.",
                    "Each research subtask should collect evidence that preserves title, date, source, link, and a short summary when available.",
                ],
            }
            workspace_context = self._build_workspace_context(workspace_root)
            if workspace_context is not None:
                planning_prompt["workspace_context"] = workspace_context
            system_prompt = (
                "You are a parent task agent planning bounded generic research subtasks. "
                "Return ONLY valid JSON with this schema: "
                '{"summary":"string","subtasks":[{"description":"string","subagent_type":"general-purpose","prompt":"string","parallel_group":"string"}]}. '
                "Produce execution-ready leaf tasks only. Do not answer the user request directly. "
                f"Write summary, description, and prompt values in {target_language} unless preserving exact names, paths, or source titles. "
                "Never emit a worker whose only job is final synthesis across sibling results. "
                "When task_hints are present, use them to separate broad discovery from detail fetch work."
            )
        else:
            target_language = llm_language_label()
            task_hint = self._resolve_planning_task_hint(
                user_message=user_message,
                request_profile=request_profile,
                default_leaf_type=orchestration_plan.default_leaf_type,
            )
            planning_prompt = {
                "planning_profile": request_profile,
                "target_language": target_language,
                "user_request": user_message,
                "recent_history": recent_history,
                "default_leaf_type": orchestration_plan.default_leaf_type,
                "allow_parallel": orchestration_plan.allow_parallel,
                "task_hints": task_hint,
                "requirements": [
                    "Decompose into bounded leaf subtasks owned by the parent task agent.",
                    "Favor parallel subtasks when there are no strong dependencies.",
                    "Workers gather evidence; the parent task agent synthesizes and writes the final answer.",
                    "If the request spans current-workspace evidence and targets or sources that are not guaranteed to exist locally, split the plan by evidence source.",
                    "Use CodeExplore only for current workspace or repository code inspection; use general-purpose for external, web, current-world, or mixed-source evidence.",
                    "Do not create a leaf worker whose job is to compare sibling outputs, merge sibling findings, or write the final answer.",
                    "For codebase architecture analysis, prefer separate subtasks for directory structure, tech stack, frontend, backend, and project progress when relevant.",
                ],
            }
            workspace_context = self._build_workspace_context(workspace_root)
            if workspace_context is not None:
                planning_prompt["workspace_context"] = workspace_context
            system_prompt = (
                "You are a parent task agent planning bounded leaf subtasks. "
                "Return ONLY valid JSON with this schema: "
                '{"summary":"string","subtasks":[{"description":"string","subagent_type":"CodeExplore|general-purpose","prompt":"string","parallel_group":"string"}]}. '
                "Do not answer the user request directly. Produce execution-ready leaf tasks only. "
                f"Write summary, description, and prompt values in {target_language} unless preserving exact names, paths, or source titles. "
                "Workers gather evidence; the parent task agent performs cross-subtask synthesis. "
                "If the request mixes local repository analysis with external targets or sources, split those evidence paths into separate leaf tasks. "
                "When task_hints are present, use them to bias the plan toward efficient bounded search sequences."
            )
        try:
            planning_message = self._render_planning_prompt_markdown(planning_prompt)
            if get_stream_sink() is not None:
                chunks: list[str] = []
                async with stream_source("planner"):
                    async for event in self._prompt_service.call_llm_stream(
                        system_prompt=system_prompt,
                        messages=[{"role": "user", "content": planning_message}],
                        disable_thinking=False,
                        json_mode=True,
                        timeout_seconds=STRUCTURED_PLANNING_TIMEOUT_SECONDS,
                        event_context={
                            "request_kind": "task_agent:planner",
                            "agent_id": self._agent_id,
                        },
                    ):
                        if event.kind == "text_delta" and event.text:
                            chunks.append(event.text)
                response = "".join(chunks)
            else:
                response = await self._prompt_service.call_llm(
                    system_prompt=system_prompt,
                    messages=[{"role": "user", "content": planning_message}],
                    disable_thinking=False,
                    json_mode=True,
                    timeout_seconds=STRUCTURED_PLANNING_TIMEOUT_SECONDS,
                    event_context={
                        "request_kind": "task_agent:planner",
                        "agent_id": self._agent_id,
                    },
                )
        except Exception as exc:
            logger.warning("Task-agent planning call failed | error=%s", exc)
            return None
        if not str(response or "").strip():
            logger.warning(
                "Task-agent planning returned empty response | user_id=%s request_preview=%s",
                self._agent_id,
                user_message[:120],
            )
            return None
        parsed_plan = self._parse_subtask_plan(response)
        if parsed_plan is None:
            logger.warning(
                "Task-agent planning returned non-executable plan | request_preview=%s response_preview=%s",
                user_message[:120],
                str(response).strip()[:300],
            )
        return parsed_plan

    async def _plan_with_plan_worker(
        self,
        *,
        user_message: str,
        user_id: str,
        session_id: str,
        run_id: str | None = None,
        run_revision: int = 0,
        workspace_root: str | None = None,
    ) -> Optional[SubtaskPlan]:
        context = self._build_agent_tool_context(
            user_id,
            session_id,
            workspace_root=workspace_root,
            run_id=run_id,
            run_revision=run_revision,
        )
        parent_task_agent_id = self._resolve_parent_task_agent_id(user_id, session_id)
        target_language = llm_language_label()
        tool_guidance = self._tool_hint_resolver.render_guidance_block(
            self._resolve_planning_task_hint(
                user_message=user_message,
                request_profile="generic",
                default_leaf_type="CodeExplore",
            )
        )
        result = await self._tool_invocation_service.invoke(
            _ServiceToolCall(name="agent", args={
                "action": "launch",
                "subagent_type": "Plan",
                "description": "plan leaf subtasks",
                "prompt": (
                    "Decompose the parent task into bounded leaf workers. "
                    "Start from the most concrete likely anchor or owning code path, then split only by neighboring responsibilities that are actually needed. "
                    "Prefer execution-ready subtasks around concrete modules, interfaces, or validation checks. "
                    "Workers gather evidence; the parent task agent handles synthesis and the final answer. "
                    "If the request mixes local workspace evidence with external or public evidence, split those into separate leaf workers instead of forcing everything into repo exploration. "
                    "Do not create a final synthesis or compare-the-findings worker that depends on sibling outputs. "
                    "Avoid generic subtasks that only gather context or summarize risks unless ambiguity remains unresolved. "
                    "Return JSON with summary, findings, evidence, gaps, next_steps, and subtasks only. "
                    f"Write all natural-language JSON values in {target_language} unless preserving exact names, paths, commands, or source titles. "
                    f"Parent task: {user_message}"
                    + (f"\n\n{tool_guidance}" if tool_guidance else "")
                ),
                "run_in_background": False,
                "target_task_agent_type": self._parent_task_agent_type,
                "target_task_agent_id": parent_task_agent_id,
                "parent_task_agent_type": self._parent_task_agent_type,
                "parent_task_agent_id": parent_task_agent_id,
                "run_id": run_id,
                "run_revision": run_revision,
            }),
            InvocationContext(
                tool_category="planning",
                task_context=TaskContext(
                    session_id=session_id,
                    turn_id=None,
                    task_id=None,
                    user_id=user_id,
                ),
                execution_context=context,
            ),
        )
        if not result.success or not isinstance(result.data, dict):
            return None
        payload = result.data.get("result")
        if not isinstance(payload, dict):
            return None
        subtasks = payload.get("subtasks")
        if not isinstance(subtasks, list) or not subtasks:
            return None
        return SubtaskPlan.from_dict(
            {
                "summary": str(payload.get("summary", "")).strip(),
                "subtasks": subtasks,
            }
        )

    def should_route_to_explore_task_agent(self, *, user_message: str, orchestration_plan: OrchestrationPlan) -> bool:
        if orchestration_plan.mode != "decompose":
            return False
        if orchestration_plan.default_leaf_type != "CodeExplore":
            return False
        lowered = user_message.lower()
        return any(
            keyword in lowered
            for keyword in [
                "architecture",
                "codebase",
                "repo",
                "跨模块",
                "跨子系统",
                "代码架构",
                "项目架构",
                "代码库",
                "目录结构",
            ]
        )

    def _normalize_subtask_plan(
        self,
        *,
        user_message: str,
        raw_plan: SubtaskPlan,
        default_leaf_type: str,
        request_profile: str,
    ) -> SubtaskPlan:
        raw_subtasks = list(raw_plan.subtasks)
        if not raw_subtasks:
            raw_subtasks = self._fallback_subtask_plan(
                user_message,
                default_leaf_type,
                request_profile=request_profile,
            )
        normalized_subtasks: list[PlannedSubtask] = []
        for item in raw_subtasks:
            description = item.description
            subtask_prompt = item.prompt
            if self._is_synthesis_only_subtask(description, subtask_prompt):
                logger.info(
                    "chat_planning.drop_synthesis_subtask",
                    description=description,
                    request_profile=request_profile,
                )
                continue
            subagent_type = self._normalize_leaf_subagent_type(
                requested_subagent_type=item.subagent_type,
                default_leaf_type=default_leaf_type,
                request_profile=request_profile,
                root_user_message=user_message,
                description=description,
                subtask_prompt=subtask_prompt,
            )
            normalized_subtasks.append(
                PlannedSubtask(
                    description=description,
                    subagent_type=subagent_type,
                    prompt=self._build_leaf_worker_prompt(
                        root_user_message=user_message,
                        subtask_description=description,
                        subtask_prompt=subtask_prompt,
                        request_profile=request_profile,
                        subagent_type=subagent_type,
                    ),
                    parallel_group=item.parallel_group,
                )
            )
        if not normalized_subtasks:
            normalized_subtasks = [
                PlannedSubtask(
                    description=item.description,
                    subagent_type=item.subagent_type,
                    prompt=self._build_leaf_worker_prompt(
                        root_user_message=user_message,
                        subtask_description=item.description,
                        subtask_prompt=item.prompt,
                        request_profile=request_profile,
                        subagent_type=item.subagent_type,
                    ),
                    parallel_group=item.parallel_group,
                )
                for item in self._fallback_subtask_plan(
                    user_message,
                    default_leaf_type,
                    request_profile=request_profile,
                )
            ]
        return SubtaskPlan(
            summary=raw_plan.summary,
            subtasks=normalized_subtasks,
        )

    def _parse_subtask_plan(self, response: str) -> Optional[SubtaskPlan]:
        raw = str(response or "").strip()
        if not raw:
            return None
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError:
            return None
        if not isinstance(payload, dict):
            return None
        subtasks = payload.get("subtasks")
        if not isinstance(subtasks, list) or not subtasks:
            return None
        normalized = SubtaskPlan.from_dict(payload)
        if not normalized.subtasks:
            return None
        return normalized
