"""Chat-owned orchestration planning and aggregation helpers."""
from __future__ import annotations

import json
import re
from typing import Any, Optional

from ....chat.workspace import get_default_chat_workspace_path
from ....core.logger import get_logger
from ....context.service import ContextAssemblyService
from ....context.scenarios import Scenario
from ....llm.streaming_events import get_stream_sink, stream_source
from ....tools.registry import ToolRegistry
from ....tools.schema import ToolExecutionContext
from ....tools.tool_hint_resolver import ToolHintResolver
from ...orchestration import PlannedSubtask, SubtaskPlan, TaskOrchestrationState
from ..common import OrchestrationPlan
from .history_service import ChatHistoryService
from .planning_heuristics import (
    build_research_seed_subtasks,
    classify_request_profile,
    extract_date_range_hint,
    is_complex_research_request,
    is_synthesis_only_subtask,
    looks_like_code_or_repo_request,
    looks_like_external_evidence_subtask,
    needs_research_fetch,
)
from .prompt_service import ChatPromptService

logger = get_logger(__name__)

STRUCTURED_PLANNING_TIMEOUT_SECONDS = 180.0


class ChatPlanningService:
    """Owns parent-task planning and aggregation for generic chat orchestration."""

    _FILE_TOOL_HINT_CANDIDATES = ["glob", "grep", "file_read"]
    _WEB_TOOL_HINT_CANDIDATES = ["web-search", "web-fetch"]

    def __init__(
        self,
        *,
        agent_id: str,
        runtime_key: str,
        context_service: ContextAssemblyService,
        prompt_service: ChatPromptService,
        history_service: ChatHistoryService,
        tool_registry: ToolRegistry,
        parent_task_agent_type: str,
        tool_hint_resolver: ToolHintResolver | None = None,
    ) -> None:
        self._agent_id = agent_id
        self._runtime_key = runtime_key
        self._context_service = context_service
        self._prompt_service = prompt_service
        self._history_service = history_service
        self._tool_registry = tool_registry
        self._parent_task_agent_type = parent_task_agent_type
        self._tool_hint_resolver = tool_hint_resolver or ToolHintResolver(tool_registry)

    async def generate_subtask_plan(
        self,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan | dict[str, Any],
        user_id: str,
        session_id: str,
        run_id: str | None = None,
        run_revision: int = 0,
        workspace_root: str | None = None,
    ) -> SubtaskPlan:
        if isinstance(orchestration_plan, dict):
            orchestration_plan = OrchestrationPlan(
                mode=str(orchestration_plan.get("mode", "direct") or "direct"),
                planner=str(orchestration_plan.get("planner", "task_agent") or "task_agent"),
                default_leaf_type=str(orchestration_plan.get("default_leaf_type", "Explore") or "Explore"),
                allow_parallel=bool(orchestration_plan.get("allow_parallel", True)),
            )
        request_profile = self._classify_request_profile(
            user_message=user_message,
            default_leaf_type=orchestration_plan.default_leaf_type,
        )
        raw_plan: Optional[SubtaskPlan] = None
        if orchestration_plan.planner == "plan_worker":
            raw_plan = await self._plan_with_plan_worker(
                user_message=user_message,
                user_id=user_id,
                session_id=session_id,
                run_id=run_id,
                run_revision=run_revision,
                workspace_root=workspace_root,
            )
        if raw_plan is None:
            raw_plan = await self._plan_with_task_agent(
                user_message=user_message,
                history=history,
                orchestration_plan=orchestration_plan,
                request_profile=request_profile,
                workspace_root=workspace_root,
            )
        if raw_plan is None:
            raw_plan = SubtaskPlan(
                summary="Fallback decomposition generated by chat task agent.",
                subtasks=self._fallback_subtask_plan(
                    user_message=user_message,
                    default_leaf_type=orchestration_plan.default_leaf_type,
                    request_profile=request_profile,
                ),
            )
        return self._normalize_subtask_plan(
            user_message=user_message,
            raw_plan=raw_plan,
            default_leaf_type=orchestration_plan.default_leaf_type,
            request_profile=request_profile,
        )

    async def aggregate_orchestration(self, state: TaskOrchestrationState) -> str:
        payload = self._prompt_service.build_aggregation_payload(state)
        history = await self._history_service.get_or_load_history(state.user_id, state.session_id)
        filtered_history = self._prompt_service.filter_history_for_aggregation(history)
        system_prompt = await self._context_service.build_system_prompt(
            user_id=state.user_id,
            session_id=state.session_id,
            user_message=state.root_user_message,
            task_category="chat",
            scenario=Scenario.ANALYSIS,
            include_tool_catalog=False,
        )
        system_prompt = self._prompt_service.build_aggregation_system_prompt(
            base_system_prompt=system_prompt,
            state=state,
            payload=payload,
        )
        messages = filtered_history or [
            {
                "role": "user",
                "content": state.root_user_message,
            }
        ]
        try:
            if get_stream_sink() is not None:
                chunks: list[str] = []
                async with stream_source("aggregator"):
                    async for event in self._prompt_service.call_llm_stream(
                        system_prompt=system_prompt,
                        messages=messages,
                        disable_thinking=False,
                    ):
                        if event.kind == "text_delta" and event.text:
                            chunks.append(event.text)
                response = "".join(chunks)
            else:
                response = await self._prompt_service.call_llm(
                    system_prompt=system_prompt,
                    messages=messages,
                    disable_thinking=False,
                )
        except Exception as exc:
            logger.warning(
                "Parent aggregation LLM call failed | orchestration_id=%s error=%s",
                state.orchestration_id,
                exc,
            )
            response = ""
        if response.strip():
            return response.strip()
        logger.warning(
            "Parent aggregation returned empty response | orchestration_id=%s completed_subtasks=%s failed_subtasks=%s",
            state.orchestration_id,
            len(payload.get("completed_subtasks", [])),
            len(payload.get("failed_subtasks", [])),
        )
        return self._prompt_service.build_aggregation_fallback(state)

    async def _plan_with_task_agent(
        self,
        *,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan,
        request_profile: str,
        workspace_root: str | None = None,
    ) -> Optional[SubtaskPlan]:
        recent_history = [
            {
                "role": str(item.get("role", "unknown")),
                "content": str(item.get("content", ""))[:400],
            }
            for item in history[-4:]
            if isinstance(item, dict) and str(item.get("content", "")).strip()
        ]
        if request_profile == "research":
            seed_subtasks = [item.to_dict() for item in self._build_research_seed_subtasks(user_message)]
            task_hint = self._resolve_planning_task_hint(
                user_message=user_message,
                request_profile=request_profile,
                default_leaf_type="general-purpose",
            )
            planning_prompt = {
                "planning_profile": "research",
                "user_request": user_message,
                "recent_history": recent_history,
                "default_leaf_type": "general-purpose",
                "allow_parallel": orchestration_plan.allow_parallel,
                "date_range_hint": self._extract_date_range_hint(user_message),
                "task_hints": task_hint,
                "seed_subtasks": seed_subtasks,
                "requirements": [
                    "Decompose into bounded, independent research subtasks that a generic worker can complete without reading sibling outputs.",
                    "Favor parallel subtasks that split by source family, verification responsibility, or retrieval angle.",
                    "Only include web-fetch when the user requests details, verification, full text, or when source summaries are likely insufficient.",
                    "The parent task agent owns cross-source synthesis. Do not create a final synthesis worker that depends on sibling worker outputs.",
                    "Each research subtask should collect evidence that preserves title, date, source, link, and a short summary when available.",
                ],
            }
            workspace_context = self._build_workspace_context(workspace_root)
            if workspace_context is not None:
                planning_prompt["workspace_context"] = workspace_context
            system_prompt = (
                "You are a parent task agent planning bounded generic research subtasks. "
                "Return ONLY valid JSON with this schema: "
                '{"summary":"string","subtasks":[{"description":"string","subagent_type":"general-purpose","prompt":"string","parallel_group":"string"}]}. '
                "Produce execution-ready leaf tasks only. Do not answer the user request directly. "
                "Never emit a worker whose only job is final synthesis across sibling results. "
                "When task_hints are present, use them to separate broad discovery from detail fetch work."
            )
        else:
            task_hint = self._resolve_planning_task_hint(
                user_message=user_message,
                request_profile=request_profile,
                default_leaf_type=orchestration_plan.default_leaf_type,
            )
            planning_prompt = {
                "planning_profile": request_profile,
                "user_request": user_message,
                "recent_history": recent_history,
                "default_leaf_type": orchestration_plan.default_leaf_type,
                "allow_parallel": orchestration_plan.allow_parallel,
                "task_hints": task_hint,
                "requirements": [
                    "Decompose into bounded leaf subtasks owned by the parent task agent.",
                    "Favor parallel subtasks when there are no strong dependencies.",
                    "Workers gather evidence; the parent task agent synthesizes and writes the final answer.",
                    "If the request spans current-workspace evidence and targets or sources that are not guaranteed to exist locally, split the plan by evidence source.",
                    "Use Explore for repo-local inspection and general-purpose for external or mixed-source evidence gathering when needed.",
                    "Do not create a leaf worker whose job is to compare sibling outputs, merge sibling findings, or write the final answer.",
                    "For codebase architecture analysis, prefer separate subtasks for directory structure, tech stack, frontend, backend, and project progress when relevant.",
                ],
            }
            workspace_context = self._build_workspace_context(workspace_root)
            if workspace_context is not None:
                planning_prompt["workspace_context"] = workspace_context
            system_prompt = (
                "You are a parent task agent planning bounded leaf subtasks. "
                "Return ONLY valid JSON with this schema: "
                '{"summary":"string","subtasks":[{"description":"string","subagent_type":"Explore|general-purpose","prompt":"string","parallel_group":"string"}]}. '
                "Do not answer the user request directly. Produce execution-ready leaf tasks only. "
                "Workers gather evidence; the parent task agent performs cross-subtask synthesis. "
                "If the request mixes local repository analysis with external targets or sources, split those evidence paths into separate leaf tasks. "
                "When task_hints are present, use them to bias the plan toward efficient bounded search sequences."
            )
        try:
            planning_message = self._render_planning_prompt_markdown(planning_prompt)
            if get_stream_sink() is not None:
                chunks: list[str] = []
                async with stream_source("planner"):
                    async for event in self._prompt_service.call_llm_stream(
                        system_prompt=system_prompt,
                        messages=[{"role": "user", "content": planning_message}],
                        disable_thinking=False,
                        json_mode=True,
                        timeout_seconds=STRUCTURED_PLANNING_TIMEOUT_SECONDS,
                    ):
                        if event.kind == "text_delta" and event.text:
                            chunks.append(event.text)
                response = "".join(chunks)
            else:
                response = await self._prompt_service.call_llm(
                    system_prompt=system_prompt,
                    messages=[{"role": "user", "content": planning_message}],
                    disable_thinking=False,
                    json_mode=True,
                    timeout_seconds=STRUCTURED_PLANNING_TIMEOUT_SECONDS,
                )
        except Exception as exc:
            logger.warning("Task-agent planning call failed | error=%s", exc)
            return None
        if not str(response or "").strip():
            logger.warning(
                "Task-agent planning returned empty response | user_id=%s request_preview=%s",
                self._agent_id,
                user_message[:120],
            )
            return None
        parsed_plan = self._parse_subtask_plan(response)
        if parsed_plan is None:
            logger.warning(
                "Task-agent planning returned non-executable plan | request_preview=%s response_preview=%s",
                user_message[:120],
                str(response).strip()[:300],
            )
        return parsed_plan

    async def _plan_with_plan_worker(
        self,
        *,
        user_message: str,
        user_id: str,
        session_id: str,
        run_id: str | None = None,
        run_revision: int = 0,
        workspace_root: str | None = None,
    ) -> Optional[SubtaskPlan]:
        context = self._build_agent_tool_context(
            user_id,
            session_id,
            workspace_root=workspace_root,
            run_id=run_id,
            run_revision=run_revision,
        )
        parent_task_agent_id = self._resolve_parent_task_agent_id(user_id, session_id)
        tool_guidance = self._tool_hint_resolver.render_guidance_block(
            self._resolve_planning_task_hint(
                user_message=user_message,
                request_profile="generic",
                default_leaf_type="Explore",
            )
        )
        result = await self._tool_registry.execute(
            "agent",
            {
                "action": "launch",
                "subagent_type": "Plan",
                "description": "plan leaf subtasks",
                "prompt": (
                    "Decompose the parent task into bounded leaf workers. "
                    "Start from the most concrete likely anchor or owning code path, then split only by neighboring responsibilities that are actually needed. "
                    "Prefer execution-ready subtasks around concrete modules, interfaces, or validation checks. "
                    "Workers gather evidence; the parent task agent handles synthesis and the final answer. "
                    "If the request mixes local workspace evidence with external or public evidence, split those into separate leaf workers instead of forcing everything into repo exploration. "
                    "Do not create a final synthesis or compare-the-findings worker that depends on sibling outputs. "
                    "Avoid generic subtasks that only gather context or summarize risks unless ambiguity remains unresolved. "
                    "Return JSON with summary, findings, evidence, gaps, next_steps, and subtasks only. "
                    f"Parent task: {user_message}"
                    + (f"\n\n{tool_guidance}" if tool_guidance else "")
                ),
                "run_in_background": False,
                "target_task_agent_type": self._parent_task_agent_type,
                "target_task_agent_id": parent_task_agent_id,
                "parent_task_agent_type": self._parent_task_agent_type,
                "parent_task_agent_id": parent_task_agent_id,
                "run_id": run_id,
                "run_revision": run_revision,
            },
            context,
        )
        if not result.success or not isinstance(result.data, dict):
            return None
        payload = result.data.get("result")
        if not isinstance(payload, dict):
            return None
        subtasks = payload.get("subtasks")
        if not isinstance(subtasks, list) or not subtasks:
            return None
        return SubtaskPlan.from_dict(
            {
                "summary": str(payload.get("summary", "")).strip(),
                "subtasks": subtasks,
            }
        )

    def should_route_to_explore_task_agent(self, *, user_message: str, orchestration_plan: OrchestrationPlan) -> bool:
        if orchestration_plan.mode != "decompose":
            return False
        if orchestration_plan.default_leaf_type != "Explore":
            return False
        lowered = user_message.lower()
        return any(
            keyword in lowered
            for keyword in [
                "architecture",
                "codebase",
                "repo",
                "跨模块",
                "跨子系统",
                "代码架构",
                "项目架构",
                "代码库",
                "目录结构",
            ]
        )

    def _normalize_subtask_plan(
        self,
        *,
        user_message: str,
        raw_plan: SubtaskPlan,
        default_leaf_type: str,
        request_profile: str,
    ) -> SubtaskPlan:
        raw_subtasks = list(raw_plan.subtasks)
        if not raw_subtasks:
            raw_subtasks = self._fallback_subtask_plan(
                user_message,
                default_leaf_type,
                request_profile=request_profile,
            )
        normalized_subtasks: list[PlannedSubtask] = []
        for item in raw_subtasks:
            description = item.description
            subtask_prompt = item.prompt
            if self._is_synthesis_only_subtask(description, subtask_prompt):
                logger.info(
                    "chat_planning.drop_synthesis_subtask",
                    description=description,
                    request_profile=request_profile,
                )
                continue
            subagent_type = self._normalize_leaf_subagent_type(
                requested_subagent_type=item.subagent_type,
                default_leaf_type=default_leaf_type,
                request_profile=request_profile,
                description=description,
                subtask_prompt=subtask_prompt,
            )
            normalized_subtasks.append(
                PlannedSubtask(
                    description=description,
                    subagent_type=subagent_type,
                    prompt=self._build_leaf_worker_prompt(
                        root_user_message=user_message,
                        subtask_description=description,
                        subtask_prompt=subtask_prompt,
                        request_profile=request_profile,
                        subagent_type=subagent_type,
                    ),
                    parallel_group=item.parallel_group,
                )
            )
        if not normalized_subtasks:
            normalized_subtasks = [
                PlannedSubtask(
                    description=item.description,
                    subagent_type=item.subagent_type,
                    prompt=self._build_leaf_worker_prompt(
                        root_user_message=user_message,
                        subtask_description=item.description,
                        subtask_prompt=item.prompt,
                        request_profile=request_profile,
                        subagent_type=item.subagent_type,
                    ),
                    parallel_group=item.parallel_group,
                )
                for item in self._fallback_subtask_plan(
                    user_message,
                    default_leaf_type,
                    request_profile=request_profile,
                )
            ]
        return SubtaskPlan(
            summary=raw_plan.summary,
            subtasks=normalized_subtasks,
        )

    def _parse_subtask_plan(self, response: str) -> Optional[SubtaskPlan]:
        raw = str(response or "").strip()
        if not raw:
            return None
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError:
            return None
        if not isinstance(payload, dict):
            return None
        subtasks = payload.get("subtasks")
        if not isinstance(subtasks, list) or not subtasks:
            return None
        normalized = SubtaskPlan.from_dict(payload)
        if not normalized.subtasks:
            return None
        return normalized

    def _fallback_subtask_plan(
        self,
        user_message: str,
        default_leaf_type: str,
        *,
        request_profile: str,
    ) -> list[PlannedSubtask]:
        is_repo_architecture = any(
            keyword in user_message.lower()
            for keyword in ["architecture", "codebase", "repo", "代码架构", "项目架构", "代码库", "目录结构"]
        )
        leaf_type = default_leaf_type if default_leaf_type in {"Explore", "general-purpose"} else "Explore"
        if request_profile == "research":
            return self._build_research_seed_subtasks(user_message)
        if is_repo_architecture:
            return [
                PlannedSubtask(
                    description="Map repository layout",
                    subagent_type="Explore",
                    prompt="Analyze the top-level directory structure, major modules, and entry folders.",
                    parallel_group="group_a",
                ),
                PlannedSubtask(
                    description="Identify technology stack",
                    subagent_type="Explore",
                    prompt="Inspect dependency manifests and boot files to identify the backend, frontend, storage, and runtime stack.",
                    parallel_group="group_a",
                ),
                PlannedSubtask(
                    description="Analyze frontend structure",
                    subagent_type="Explore",
                    prompt="Focus on frontend organization, bootstrap flow, routing, and the main UI entry points.",
                    parallel_group="group_a",
                ),
                PlannedSubtask(
                    description="Analyze backend modules",
                    subagent_type="Explore",
                    prompt="Focus on backend module boundaries, runtime startup, task agent chain, and the main execution flow.",
                    parallel_group="group_a",
                ),
                PlannedSubtask(
                    description="Inspect project progress",
                    subagent_type="Explore",
                    prompt="Look for docs, progress trackers, release notes, or TODO-style files that indicate the current project status and recent progress.",
                    parallel_group="group_a",
                ),
            ]
        return [
            PlannedSubtask(
                description="Locate the primary anchor",
                subagent_type=leaf_type,
                prompt="Find the smallest set of files, symbols, or entry modules most likely to control the requested behavior or answer.",
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Trace the owning implementation path",
                subagent_type=leaf_type,
                prompt="Follow the code path that directly computes, routes, or controls the requested behavior, pulling in only the nearby dependencies needed to explain it.",
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Validate gaps and edge cases",
                subagent_type=leaf_type,
                prompt="Validate important edge cases, unresolved assumptions, and remaining gaps from source evidence instead of repeating broad summary prose.",
                parallel_group="group_b",
            ),
        ]

    def _build_leaf_worker_prompt(
        self,
        *,
        root_user_message: str,
        subtask_description: str,
        subtask_prompt: str,
        request_profile: str,
        subagent_type: str | None = None,
    ) -> str:
        tool_guidance = self._tool_hint_resolver.render_guidance_block(
            self._resolve_leaf_task_hint(
                root_user_message=root_user_message,
                subtask_prompt=subtask_prompt,
                request_profile=request_profile,
                subagent_type=subagent_type,
            )
        )
        if request_profile == "research":
            date_range_hint = self._extract_date_range_hint(root_user_message)
            lines = [
                f"Parent user request: {root_user_message}",
                f"Assigned subtask: {subtask_description}",
                "Task-specific instructions:",
                subtask_prompt,
                *( [tool_guidance] if tool_guidance else [] ),
                "Success criteria:",
                "- Stay strictly within this subtask scope.",
                "- Prefer web-search for discovery and only use web-fetch when the task explicitly requires article details or verification.",
                "- When a normalized date range is available, pass it to web-search via `start_date` and `end_date` instead of relying on a fuzzy year in the query.",
                "- Preserve concrete evidence for each usable result: title, date, source, canonical link, and a short summary when available.",
                "- In findings, use `title` for the headline, `detail` for `DATE | SOURCE | SUMMARY`, and `path` for the canonical article URL.",
                "- If the available evidence is thin or conflicting, record it in gaps instead of guessing.",
                "- Gather evidence directly from your own sources; do not depend on sibling worker outputs or produce the final cross-source synthesis.",
                "- Do not fabricate publication dates, links, or sources.",
            ]
            if date_range_hint:
                lines.insert(
                    4,
                    f"Normalized date range: {date_range_hint['start_date']} to {date_range_hint['end_date']} (inclusive).",
                )
            return "\n".join(lines)
        if str(subagent_type or "").strip() == "general-purpose":
            return "\n".join(
                [
                    f"Parent user request: {root_user_message}",
                    f"Assigned subtask: {subtask_description}",
                    "Task-specific instructions:",
                    subtask_prompt,
                    *([tool_guidance] if tool_guidance else []),
                    "Success criteria:",
                    "- Stay strictly within this subtask scope.",
                    "- Choose the evidence sources that fit the task: current workspace, official docs, public sources, or a bounded combination.",
                    "- If the target is not guaranteed to exist in the current workspace, do not assume local files exist; use external discovery first.",
                    "- When you reference repo-local code, verify the exact file or symbol before relying on it.",
                    "- When you reference external evidence, preserve title, date, source, and canonical link when available.",
                    "- Gather evidence directly; do not depend on sibling worker outputs or write the final cross-worker synthesis.",
                    "- Prefer validated findings over speculation.",
                    "- If information is missing, put it into gaps instead of guessing.",
                ]
            )
        return "\n".join(
            [
                f"Parent user request: {root_user_message}",
                f"Assigned subtask: {subtask_description}",
                "Task-specific instructions:",
                subtask_prompt,
                *( [tool_guidance] if tool_guidance else [] ),
                "Success criteria:",
                "- Stay strictly within this subtask scope.",
                "- Start from the most concrete anchor available: an entry file, symbol, path, interface, or directly controlling module.",
                "- If you name a file, symbol, route, config key, or flag, verify it exists in the current code before relying on it.",
                "- Prefer focused glob/grep/read steps over broad repository scans.",
                "- Use absolute file paths in findings and evidence when you reference code.",
                "- Prefer validated findings over speculation.",
                "- If information is missing, put it into gaps instead of guessing.",
                "- Do not duplicate likely sibling subtasks unless it is necessary evidence.",
            ]
        )

    def _resolve_planning_task_hint(
        self,
        *,
        user_message: str,
        request_profile: str,
        default_leaf_type: str,
    ) -> dict[str, Any]:
        available_tools = (
            list(self._WEB_TOOL_HINT_CANDIDATES)
            if request_profile == "research"
            else self._candidate_file_tools(default_leaf_type, user_message)
        )
        return self._tool_hint_resolver.resolve(
            user_message=user_message,
            available_tools=available_tools,
            request_profile=request_profile,
        )

    def _resolve_leaf_task_hint(
        self,
        *,
        root_user_message: str,
        subtask_prompt: str,
        request_profile: str,
        subagent_type: str | None,
    ) -> dict[str, Any]:
        if request_profile == "research":
            available_tools = list(self._WEB_TOOL_HINT_CANDIDATES)
        elif str(subagent_type or "").strip() == "general-purpose":
            available_tools = list(self._WEB_TOOL_HINT_CANDIDATES)
        elif str(subagent_type or "").strip() == "Explore" or self._looks_like_code_or_repo_request(root_user_message, subtask_prompt):
            available_tools = list(self._FILE_TOOL_HINT_CANDIDATES)
        else:
            available_tools = []
        return self._tool_hint_resolver.resolve(
            user_message=root_user_message,
            available_tools=available_tools,
            request_profile=request_profile,
        )

    def _candidate_file_tools(self, default_leaf_type: str, user_message: str) -> list[str]:
        if default_leaf_type == "Explore" or self._looks_like_code_or_repo_request(user_message, ""):
            return list(self._FILE_TOOL_HINT_CANDIDATES)
        return []

    def _build_workspace_context(self, workspace_root: str | None) -> dict[str, str] | None:
        normalized = str(workspace_root or "").strip()
        if not normalized:
            return None
        workspace_name = re.sub(r"[^A-Za-z0-9._-]+", " ", normalized.rstrip("/").split("/")[-1]).strip()
        return {
            "workspace_root": normalized,
            "workspace_name": workspace_name or normalized,
        }

    def _render_planning_prompt_markdown(self, planning_prompt: dict[str, Any]) -> str:
        lines: list[str] = ["# Planning Brief", ""]

        planning_profile = str(planning_prompt.get("planning_profile") or "generic").strip()
        default_leaf_type = str(planning_prompt.get("default_leaf_type") or "Explore").strip()
        allow_parallel = bool(planning_prompt.get("allow_parallel", True))

        lines.extend([
            "## Planning Context",
            f"- Planning profile: {planning_profile}",
            f"- Default leaf type: {default_leaf_type}",
            f"- Parallel execution allowed: {'yes' if allow_parallel else 'no'}",
            "",
        ])

        user_request = str(planning_prompt.get("user_request") or "").strip()
        if user_request:
            lines.extend([
                "## User Request",
                user_request,
                "",
            ])

        recent_history = planning_prompt.get("recent_history") if isinstance(planning_prompt.get("recent_history"), list) else []
        if recent_history:
            lines.append("## Recent History")
            for item in recent_history:
                if not isinstance(item, dict):
                    continue
                role = str(item.get("role") or "unknown").strip() or "unknown"
                content = str(item.get("content") or "").strip()
                if content:
                    lines.append(f"- {role}: {content}")
            lines.append("")

        workspace_context = planning_prompt.get("workspace_context") if isinstance(planning_prompt.get("workspace_context"), dict) else None
        if workspace_context:
            lines.extend([
                "## Workspace Context",
                f"- Workspace root: {str(workspace_context.get('workspace_root') or '').strip()}",
                f"- Workspace name: {str(workspace_context.get('workspace_name') or '').strip()}",
                "",
            ])

        date_range_hint = planning_prompt.get("date_range_hint") if isinstance(planning_prompt.get("date_range_hint"), dict) else None
        if date_range_hint:
            lines.extend([
                "## Date Range Hint",
                f"- Start date: {str(date_range_hint.get('start_date') or '').strip()}",
                f"- End date: {str(date_range_hint.get('end_date') or '').strip()}",
                "",
            ])

        task_hint_lines = self._render_planning_task_hint_markdown(planning_prompt.get("task_hints"))
        if task_hint_lines:
            lines.append("## Task Hints")
            lines.extend(task_hint_lines)
            lines.append("")

        seed_subtasks = planning_prompt.get("seed_subtasks") if isinstance(planning_prompt.get("seed_subtasks"), list) else []
        if seed_subtasks:
            lines.append("## Seed Subtasks")
            for index, item in enumerate(seed_subtasks, start=1):
                if not isinstance(item, dict):
                    continue
                description = str(item.get("description") or f"Seed subtask {index}").strip()
                subagent_type = str(item.get("subagent_type") or "").strip()
                parallel_group = str(item.get("parallel_group") or "").strip()
                prompt = str(item.get("prompt") or "").strip()
                summary_parts = [description]
                if subagent_type:
                    summary_parts.append(f"type={subagent_type}")
                if parallel_group:
                    summary_parts.append(f"parallel_group={parallel_group}")
                lines.append(f"- {' | '.join(summary_parts)}")
                if prompt:
                    lines.append(f"  Prompt: {prompt}")
            lines.append("")

        requirements = planning_prompt.get("requirements") if isinstance(planning_prompt.get("requirements"), list) else []
        if requirements:
            lines.append("## Requirements")
            for item in requirements:
                requirement = str(item or "").strip()
                if requirement:
                    lines.append(f"- {requirement}")
            lines.append("")

        lines.extend([
            "## Output Contract",
            "- Return ONLY valid JSON that matches the system prompt schema.",
            "- Produce execution-ready leaf tasks rather than answering the user directly.",
        ])
        return "\n".join(lines).strip()

    @staticmethod
    def _render_planning_task_hint_markdown(task_hint: Any) -> list[str]:
        if not isinstance(task_hint, dict):
            return []

        lines: list[str] = []
        field_labels = [
            ("task_intent", "Task intent"),
            ("domain", "Domain"),
            ("operation", "Operation"),
            ("target_locality", "Target locality"),
            ("preferred_resolution_order", "Preferred resolution order"),
        ]
        for field_name, label in field_labels:
            value = str(task_hint.get(field_name) or "").strip()
            if value:
                lines.append(f"- {label}: {value}")

        if "requires_clarification" in task_hint:
            lines.append(f"- Requires clarification: {'yes' if bool(task_hint.get('requires_clarification')) else 'no'}")

        tool_hints = task_hint.get("tool_hints") if isinstance(task_hint.get("tool_hints"), list) else []
        if tool_hints:
            lines.append("- Preferred tools:")
            for item in tool_hints:
                if not isinstance(item, dict):
                    continue
                tool_name = str(item.get("tool") or "unknown").strip()
                priority = item.get("priority")
                reason = str(item.get("reason") or "").strip()
                tool_line = f"  - {tool_name}"
                if priority not in (None, ""):
                    tool_line += f" (priority {priority})"
                if reason:
                    tool_line += f": {reason}"
                lines.append(tool_line)
        return lines

    def _normalize_leaf_subagent_type(
        self,
        *,
        requested_subagent_type: str | None,
        default_leaf_type: str,
        request_profile: str,
        description: str,
        subtask_prompt: str,
    ) -> str:
        subagent_type = str(requested_subagent_type or default_leaf_type).strip()
        if subagent_type not in {"Explore", "general-purpose"}:
            subagent_type = default_leaf_type if default_leaf_type in {"Explore", "general-purpose"} else "Explore"
        if request_profile == "research":
            return "general-purpose"
        if subagent_type == "Explore" and self._looks_like_external_evidence_subtask(description, subtask_prompt):
            return "general-purpose"
        return subagent_type

    def _looks_like_external_evidence_subtask(self, description: str, subtask_prompt: str) -> bool:
        return looks_like_external_evidence_subtask(description, subtask_prompt)

    def _is_synthesis_only_subtask(self, description: str, subtask_prompt: str) -> bool:
        return is_synthesis_only_subtask(description, subtask_prompt)

    @staticmethod
    def _looks_like_code_or_repo_request(user_message: str, subtask_prompt: str) -> bool:
        return looks_like_code_or_repo_request(user_message, subtask_prompt)

    def _classify_request_profile(self, *, user_message: str, default_leaf_type: str) -> str:
        return classify_request_profile(user_message=user_message, default_leaf_type=default_leaf_type)

    def _is_complex_research_request(self, user_message: str) -> bool:
        return is_complex_research_request(user_message)

    def _needs_research_fetch(self, user_message: str) -> bool:
        return needs_research_fetch(user_message)

    def _build_research_seed_subtasks(self, user_message: str) -> list[PlannedSubtask]:
        return build_research_seed_subtasks(user_message)

    def _extract_date_range_hint(self, user_message: str) -> Optional[dict[str, str]]:
        return extract_date_range_hint(user_message)

    def _build_agent_tool_context(
        self,
        user_id: str,
        session_id: str,
        workspace_root: str | None = None,
        *,
        run_id: str | None = None,
        run_revision: int = 0,
    ) -> ToolExecutionContext:
        parent_task_agent_id = self._resolve_parent_task_agent_id(user_id, session_id)
        return ToolExecutionContext(
            agent_id=self._runtime_key,
            workspace=str(workspace_root or "").strip(),
            env_vars={
                "user_id": user_id,
                "session_id": session_id,
                "target_task_agent_type": self._parent_task_agent_type,
                "target_task_agent_id": parent_task_agent_id,
                "parent_task_agent_type": self._parent_task_agent_type,
                "parent_task_agent_id": parent_task_agent_id,
                "run_id": run_id or "",
                "run_revision": str(run_revision),
            },
            permissions=["authenticated"],
        )

    def _resolve_parent_task_agent_id(self, user_id: str, session_id: str) -> str:
        if self._parent_task_agent_type == "chat" and str(session_id).strip():
            return session_id
        return user_id
