"""Unified plugin runtime exports.

Public API for both internal backend code and plugin authors.
All contract types originate from ``magi-plugin-sdk``.
"""

from magi_plugin_sdk import (  # noqa: F401
    ActivationFlowSpec,
    ActivationFirstContextSpec,
    ContributionType,
    ExtractionProfileSpec,
    ExtensionFieldOption,
    ExtensionFieldSpec,
    HistoryImportParseResult,
    HistoryImportRecord,
    HistoryImportSource,
    HistoryImporter,
    HistoryImporterSpec,
    Plugin,
    PluginContribution,
    PluginDisplayGroupSpec,
    PluginI18n,
    PluginManifest,
    PluginPackageState,
    PluginRegistryEntry,
    PluginRegistryIndex,
    PluginSettingsActionResult,
    PluginSettingsActionSpec,
    PluginSettingsResourcePayload,
    PluginSettingsResourceSpec,
    SensorSpec,
    SettingsUIBlockSpec,
    SuggestionSurfaceSpec,
    SuggestionSurfacesSpec,
    UserContentClearContext,
    UserContentClearRequest,
    configure_basic_logging,
    get_logger,
)
from .manager import PluginManager
from .projections import PluginProjectionService
from .sensors import SensorRegistry
from .history_importers import HistoryImporterRegistry

__all__ = [
    "ActivationFlowSpec",
    "ActivationFirstContextSpec",
    "ContributionType",
    "ExtractionProfileSpec",
    "ExtensionFieldOption",
    "ExtensionFieldSpec",
    "HistoryImportParseResult",
    "HistoryImportRecord",
    "HistoryImportSource",
    "HistoryImporter",
    "HistoryImporterSpec",
    "Plugin",
    "PluginContribution",
    "PluginDisplayGroupSpec",
    "PluginI18n",
    "PluginManifest",
    "PluginManager",
    "PluginPackageState",
    "PluginProjectionService",
    "PluginRegistryEntry",
    "PluginRegistryIndex",
    "PluginSettingsActionResult",
    "PluginSettingsActionSpec",
    "PluginSettingsResourcePayload",
    "PluginSettingsResourceSpec",
    "SensorRegistry",
    "HistoryImporterRegistry",
    "SensorSpec",
    "SettingsUIBlockSpec",
    "SuggestionSurfaceSpec",
    "SuggestionSurfacesSpec",
    "UserContentClearContext",
    "UserContentClearRequest",
    "configure_basic_logging",
    "get_logger",
]
