"""Chat-owned orchestration planning and aggregation helpers."""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Optional

from magi.core.logger import get_logger
from magi.context.service import ContextAssemblyService
from magi.context.scenarios import Scenario
from magi.events.domain_payloads import TaskContext
from magi.i18n import llm_language_label
from magi.llm.streaming_events import get_stream_sink, stream_source
from magi.tools.registry import ToolRegistry
from magi.tools.tool_hint_resolver import ToolHintResolver
from magi.utils.diagnostic_logging import full_content_logging_enabled
from magi.agent.execution.tool_invocation_service import (
    InvocationContext,
    ToolCall as _ServiceToolCall,
)
from magi.agent.orchestration import PlannedSubtask, SubtaskPlan, TaskOrchestrationState
from magi.agent.task_agents.common import OrchestrationPlan
from .context_assembler import ChatContextAssembler
from .planning_prompts import ChatPlanningPromptMixin
from .prompt_service import ChatPromptService

logger = get_logger(__name__)

STRUCTURED_PLANNING_TIMEOUT_SECONDS = 180.0


@dataclass(slots=True)
class _TaskAgentPlanningRequest:
    system_prompt: str
    planning_prompt: dict[str, Any]


@dataclass(slots=True)
class _AggregationInputs:
    payload: dict[str, Any]
    filtered_history: list[dict[str, str]]
    base_system_prompt: str


class ChatPlanningService(ChatPlanningPromptMixin):
    """Owns parent-task planning and aggregation for generic chat orchestration."""

    _FILE_TOOL_HINT_CANDIDATES = ["glob", "grep", "file_read"]
    _WEB_TOOL_HINT_CANDIDATES = ["web-search", "web-fetch"]

    def __init__(
        self,
        *,
        agent_id: str,
        runtime_key: str,
        context_service: ContextAssemblyService,
        prompt_service: ChatPromptService,
        context_assembler: ChatContextAssembler,
        tool_registry: ToolRegistry,
        parent_task_agent_type: str,
        tool_hint_resolver: ToolHintResolver | None = None,
    ) -> None:
        self._agent_id = agent_id
        self._runtime_key = runtime_key
        self._context_service = context_service
        self._prompt_service = prompt_service
        self._context_assembler = context_assembler
        self._tool_registry = tool_registry
        self._parent_task_agent_type = parent_task_agent_type
        self._tool_hint_resolver = tool_hint_resolver or ToolHintResolver(tool_registry)

    @property
    def _tool_invocation_service(self):
        from magi.agent.execution.tool_invocation_service import get_tool_invocation_service

        if not hasattr(self, "_tool_invocation_service_cached"):
            self._tool_invocation_service_cached = get_tool_invocation_service(self._tool_registry)
        return self._tool_invocation_service_cached

    async def generate_subtask_plan(
        self,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan,
        user_id: str,
        session_id: str,
        run_id: str | None = None,
        run_revision: int = 0,
        workspace_root: str | None = None,
    ) -> SubtaskPlan:
        request_profile = self._classify_request_profile(
            user_message=user_message,
            default_leaf_type=orchestration_plan.default_leaf_type,
        )
        raw_plan: Optional[SubtaskPlan] = None
        if orchestration_plan.planner == "plan_worker":
            raw_plan = await self._plan_with_plan_worker(
                user_message=user_message,
                user_id=user_id,
                session_id=session_id,
                run_id=run_id,
                run_revision=run_revision,
                workspace_root=workspace_root,
            )
        if raw_plan is None:
            raw_plan = await self._plan_with_task_agent(
                user_message=user_message,
                history=history,
                orchestration_plan=orchestration_plan,
                request_profile=request_profile,
                workspace_root=workspace_root,
            )
        if raw_plan is None:
            raw_plan = SubtaskPlan(
                summary="Fallback decomposition generated by chat task agent.",
                subtasks=self._fallback_subtask_plan(
                    user_message=user_message,
                    default_leaf_type=orchestration_plan.default_leaf_type,
                    request_profile=request_profile,
                ),
            )
        return self._normalize_subtask_plan(
            user_message=user_message,
            raw_plan=raw_plan,
            default_leaf_type=orchestration_plan.default_leaf_type,
            request_profile=request_profile,
        )

    async def aggregate_orchestration(self, state: TaskOrchestrationState) -> str:
        state.metadata["aggregation_streamed"] = False
        inputs = await self._build_aggregation_inputs(state)
        if self._prompt_service.should_use_failure_status_path(inputs.payload):
            return await self._render_failure_status(
                state=state,
                payload=inputs.payload,
                base_system_prompt=inputs.base_system_prompt,
                filtered_history=inputs.filtered_history,
            )
        system_prompt = self._prompt_service.build_aggregation_system_prompt(
            base_system_prompt=inputs.base_system_prompt,
            state=state,
            payload=inputs.payload,
        )
        messages = self._prompt_service.build_aggregation_messages(
            history_messages=inputs.filtered_history,
            state=state,
            payload=inputs.payload,
        )
        try:
            response = await self._call_aggregation_llm(
                state=state,
                system_prompt=system_prompt,
                messages=messages,
                disable_thinking=False,
                request_kind="task_agent:aggregator",
                stream_label="aggregator",
            )
        except Exception as exc:
            logger.warning(
                "Parent aggregation LLM call failed | orchestration_id=%s error=%s",
                state.orchestration_id,
                exc,
            )
            response = ""
        return self._aggregation_response_or_fallback(state, inputs.payload, response)

    async def _build_aggregation_inputs(
        self,
        state: TaskOrchestrationState,
    ) -> _AggregationInputs:
        payload = self._prompt_service.build_aggregation_payload(state)
        history = await self._context_assembler.get_or_load_history(state.user_id, state.session_id)
        filtered_history = self._prompt_service.filter_history_for_aggregation(history)
        base_system_prompt = await self._context_service.build_system_prompt(
            user_id=state.user_id,
            session_id=state.session_id,
            user_message=state.root_user_message,
            task_category="analysis",
            scenario=Scenario.ANALYSIS,
            include_tool_catalog=False,
            persona_id=str(state.metadata.get("persona_id") or "").strip() or None,
        )
        return _AggregationInputs(
            payload=payload,
            filtered_history=filtered_history,
            base_system_prompt=base_system_prompt,
        )

    def _aggregation_response_or_fallback(
        self,
        state: TaskOrchestrationState,
        payload: dict[str, Any],
        response: str,
    ) -> str:
        if response.strip():
            return response.strip()
        state.metadata["aggregation_streamed"] = False
        logger.warning(
            "Parent aggregation returned empty response | orchestration_id=%s completed_subtasks=%s failed_subtasks=%s",
            state.orchestration_id,
            len(payload.get("completed_subtasks", [])),
            len(payload.get("failed_subtasks", [])),
        )
        return self._prompt_service.build_aggregation_fallback(state)

    async def _call_aggregation_llm(
        self,
        *,
        state: TaskOrchestrationState,
        system_prompt: str,
        messages: list[dict[str, str]],
        disable_thinking: bool,
        request_kind: str,
        stream_label: str,
    ) -> str:
        event_context = {
            "request_kind": request_kind,
            "agent_id": self._agent_id,
            "session_id": state.session_id,
        }
        if get_stream_sink() is not None:
            response = await self._call_aggregation_llm_stream(
                system_prompt=system_prompt,
                messages=messages,
                disable_thinking=disable_thinking,
                event_context=event_context,
                stream_label=stream_label,
            )
            state.metadata["aggregation_streamed"] = bool(response.strip())
            return response
        return await self._prompt_service.call_llm(
            system_prompt=system_prompt,
            messages=messages,
            disable_thinking=disable_thinking,
            event_context=event_context,
        )

    async def _call_aggregation_llm_stream(
        self,
        *,
        system_prompt: str,
        messages: list[dict[str, str]],
        disable_thinking: bool,
        event_context: dict[str, Any],
        stream_label: str,
    ) -> str:
        chunks: list[str] = []
        async with stream_source(stream_label):
            async for event in self._prompt_service.call_llm_stream(
                system_prompt=system_prompt,
                messages=messages,
                disable_thinking=disable_thinking,
                event_context=event_context,
            ):
                if event.kind == "text_delta" and event.text:
                    chunks.append(event.text)
        return "".join(chunks)

    async def _render_failure_status(
        self,
        *,
        state: TaskOrchestrationState,
        payload: dict[str, Any],
        base_system_prompt: str,
        filtered_history: list[dict[str, str]],
    ) -> str:
        system_prompt = self._prompt_service.build_failure_status_system_prompt(
            base_system_prompt=base_system_prompt,
            state=state,
        )
        messages = self._prompt_service.build_failure_status_messages(
            history_messages=filtered_history,
            state=state,
            payload=payload,
        )
        try:
            response = await self._call_aggregation_llm(
                state=state,
                system_prompt=system_prompt,
                messages=messages,
                disable_thinking=True,
                request_kind="task_agent:failure_status",
                stream_label="failure_status",
            )
        except Exception as exc:
            logger.warning(
                "Parent failure-status LLM call failed | orchestration_id=%s error=%s",
                state.orchestration_id,
                exc,
            )
            response = ""
        return self._failure_status_response_or_fallback(state, payload, response)

    def _failure_status_response_or_fallback(
        self,
        state: TaskOrchestrationState,
        payload: dict[str, Any],
        response: str,
    ) -> str:
        if response.strip():
            return response.strip()
        state.metadata["aggregation_streamed"] = False
        logger.warning(
            "Parent failure-status returned empty response | orchestration_id=%s failed_subtasks=%s",
            state.orchestration_id,
            len(payload.get("failed_subtasks", [])),
        )
        return self._prompt_service.build_failure_status_fallback(state, payload)

    async def _plan_with_task_agent(
        self,
        *,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan,
        request_profile: str,
        workspace_root: str | None = None,
    ) -> Optional[SubtaskPlan]:
        # TODO(phase-B): thread `control: RunControl` into this planner so
        # mid-LLM retract/cancel observe the signal directly rather than
        # relying on the wrapper `except RetractRaised` in TaskOrchestrator.
        # Today: signal observed only at the next worker-await boundary or
        # via the wrapper if CancellableLLMClient raises mid-stream.
        planning_request = self._build_task_agent_planning_request(
            user_message=user_message,
            history=history,
            orchestration_plan=orchestration_plan,
            request_profile=request_profile,
            workspace_root=workspace_root,
        )
        try:
            response = await self._call_task_agent_planner(planning_request)
        except Exception as exc:
            logger.warning("Task-agent planning call failed | error=%s", exc)
            return None
        return self._parse_task_agent_planning_response(
            response=response,
            user_message=user_message,
        )

    def _build_task_agent_planning_request(
        self,
        *,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan,
        request_profile: str,
        workspace_root: str | None,
    ) -> _TaskAgentPlanningRequest:
        recent_history = _recent_planning_history(history)
        if request_profile == "research":
            return self._build_research_planning_request(
                user_message=user_message,
                recent_history=recent_history,
                allow_parallel=orchestration_plan.allow_parallel,
                workspace_root=workspace_root,
            )
        return self._build_generic_planning_request(
            user_message=user_message,
            recent_history=recent_history,
            orchestration_plan=orchestration_plan,
            request_profile=request_profile,
            workspace_root=workspace_root,
        )

    def _build_research_planning_request(
        self,
        *,
        user_message: str,
        recent_history: list[dict[str, str]],
        allow_parallel: bool,
        workspace_root: str | None,
    ) -> _TaskAgentPlanningRequest:
        target_language = llm_language_label()
        seed_subtasks = [
            item.to_dict() for item in self._build_research_seed_subtasks(user_message)
        ]
        planning_prompt = {
            "planning_profile": "research",
            "target_language": target_language,
            "user_request": user_message,
            "recent_history": recent_history,
            "default_leaf_type": "general-purpose",
            "allow_parallel": allow_parallel,
            "date_range_hint": self._extract_date_range_hint(user_message),
            "task_hints": self._resolve_planning_task_hint(
                user_message=user_message,
                request_profile="research",
                default_leaf_type="general-purpose",
            ),
            "seed_subtasks": seed_subtasks,
            "requirements": [
                "Decompose into bounded, independent research subtasks that a generic worker can complete without reading sibling outputs.",
                "Favor parallel subtasks that split by source family, verification responsibility, or retrieval angle.",
                "Only include web-fetch when the user requests details, verification, full text, or when source summaries are likely insufficient.",
                "The parent task agent owns cross-source synthesis. Do not create a final synthesis worker that depends on sibling worker outputs.",
                "Each research subtask should collect evidence that preserves title, date, source, link, and a short summary when available.",
            ],
        }
        _attach_workspace_context(planning_prompt, self._build_workspace_context(workspace_root))
        return _TaskAgentPlanningRequest(
            planning_prompt=planning_prompt,
            system_prompt=(
                "You are a parent task agent planning bounded generic research subtasks. "
                "Return ONLY valid JSON with this schema: "
                '{"summary":"string","subtasks":[{"description":"string","subagent_type":"general-purpose","prompt":"string","parallel_group":"string"}]}. '
                "Produce execution-ready leaf tasks only. Do not answer the user request directly. "
                f"Write summary, description, and prompt values in {target_language} unless preserving exact names, paths, or source titles. "
                "Never emit a worker whose only job is final synthesis across sibling results. "
                "When task_hints are present, use them to separate broad discovery from detail fetch work."
            ),
        )

    def _build_generic_planning_request(
        self,
        *,
        user_message: str,
        recent_history: list[dict[str, str]],
        orchestration_plan: OrchestrationPlan,
        request_profile: str,
        workspace_root: str | None,
    ) -> _TaskAgentPlanningRequest:
        target_language = llm_language_label()
        planning_prompt = {
            "planning_profile": request_profile,
            "target_language": target_language,
            "user_request": user_message,
            "recent_history": recent_history,
            "default_leaf_type": orchestration_plan.default_leaf_type,
            "allow_parallel": orchestration_plan.allow_parallel,
            "task_hints": self._resolve_planning_task_hint(
                user_message=user_message,
                request_profile=request_profile,
                default_leaf_type=orchestration_plan.default_leaf_type,
            ),
            "requirements": [
                "Decompose into bounded leaf subtasks owned by the parent task agent.",
                "Favor parallel subtasks when there are no strong dependencies.",
                "Workers gather evidence; the parent task agent synthesizes and writes the final answer.",
                "If the request spans current-workspace evidence and targets or sources that are not guaranteed to exist locally, split the plan by evidence source.",
                "Use CodeExplore only for current workspace or repository code inspection; use general-purpose for external, web, current-world, or mixed-source evidence.",
                "Do not create a leaf worker whose job is to compare sibling outputs, merge sibling findings, or write the final answer.",
                "For codebase architecture analysis, prefer separate subtasks for directory structure, tech stack, frontend, backend, and project progress when relevant.",
            ],
        }
        _attach_workspace_context(planning_prompt, self._build_workspace_context(workspace_root))
        return _TaskAgentPlanningRequest(
            planning_prompt=planning_prompt,
            system_prompt=(
                "You are a parent task agent planning bounded leaf subtasks. "
                "Return ONLY valid JSON with this schema: "
                '{"summary":"string","subtasks":[{"description":"string","subagent_type":"CodeExplore|general-purpose","prompt":"string","parallel_group":"string"}]}. '
                "Do not answer the user request directly. Produce execution-ready leaf tasks only. "
                f"Write summary, description, and prompt values in {target_language} unless preserving exact names, paths, or source titles. "
                "Workers gather evidence; the parent task agent performs cross-subtask synthesis. "
                "If the request mixes local repository analysis with external targets or sources, split those evidence paths into separate leaf tasks. "
                "When task_hints are present, use them to bias the plan toward efficient bounded search sequences."
            ),
        )

    async def _call_task_agent_planner(
        self,
        planning_request: _TaskAgentPlanningRequest,
    ) -> str:
        planning_message = self._render_planning_prompt_markdown(planning_request.planning_prompt)
        if get_stream_sink() is not None:
            chunks: list[str] = []
            async with stream_source("planner"):
                async for event in self._prompt_service.call_llm_stream(
                    system_prompt=planning_request.system_prompt,
                    messages=[{"role": "user", "content": planning_message}],
                    disable_thinking=False,
                    json_mode=True,
                    timeout_seconds=STRUCTURED_PLANNING_TIMEOUT_SECONDS,
                    event_context={
                        "request_kind": "task_agent:planner",
                        "agent_id": self._agent_id,
                    },
                ):
                    if event.kind == "text_delta" and event.text:
                        chunks.append(event.text)
            return "".join(chunks)
        return await self._prompt_service.call_llm(
            system_prompt=planning_request.system_prompt,
            messages=[{"role": "user", "content": planning_message}],
            disable_thinking=False,
            json_mode=True,
            timeout_seconds=STRUCTURED_PLANNING_TIMEOUT_SECONDS,
            event_context={
                "request_kind": "task_agent:planner",
                "agent_id": self._agent_id,
            },
        )

    def _parse_task_agent_planning_response(
        self,
        *,
        response: str,
        user_message: str,
    ) -> Optional[SubtaskPlan]:
        if not str(response or "").strip():
            if full_content_logging_enabled():
                logger.warning(
                    "Task-agent planning returned empty response | "
                    "user_id=%s request_preview=%s",
                    self._agent_id,
                    user_message[:120],
                )
            else:
                logger.warning(
                    "Task-agent planning returned empty response | "
                    "user_id=%s request_chars=%d",
                    self._agent_id,
                    len(user_message),
                )
            return None
        parsed_plan = self._parse_subtask_plan(response)
        if parsed_plan is None:
            if full_content_logging_enabled():
                logger.warning(
                    "Task-agent planning returned non-executable plan | "
                    "request_preview=%s response_preview=%s",
                    user_message[:120],
                    str(response).strip()[:300],
                )
            else:
                logger.warning(
                    "Task-agent planning returned non-executable plan | "
                    "request_chars=%d response_chars=%d",
                    len(user_message),
                    len(str(response)),
                )
        return parsed_plan

    async def _plan_with_plan_worker(
        self,
        *,
        user_message: str,
        user_id: str,
        session_id: str,
        run_id: str | None = None,
        run_revision: int = 0,
        workspace_root: str | None = None,
    ) -> Optional[SubtaskPlan]:
        # TODO(phase-B): thread `control: RunControl` into this planner so
        # mid-LLM retract/cancel observe the signal directly rather than
        # relying on the wrapper `except RetractRaised` in TaskOrchestrator.
        # Today: signal observed only at the next worker-await boundary or
        # via the wrapper if CancellableLLMClient raises mid-stream.
        context = self._build_agent_tool_context(
            user_id,
            session_id,
            workspace_root=workspace_root,
            run_id=run_id,
            run_revision=run_revision,
        )
        parent_task_agent_id = self._resolve_parent_task_agent_id(user_id, session_id)
        result = await self._tool_invocation_service.invoke(
            self._build_plan_worker_tool_call(
                user_message=user_message,
                parent_task_agent_id=parent_task_agent_id,
                run_id=run_id,
                run_revision=run_revision,
            ),
            InvocationContext(
                tool_category="planning",
                task_context=TaskContext(
                    session_id=session_id,
                    turn_id=None,
                    task_id=None,
                    user_id=user_id,
                ),
                execution_context=context,
            ),
        )
        return self._subtask_plan_from_plan_worker_result(result)

    def _build_plan_worker_tool_call(
        self,
        *,
        user_message: str,
        parent_task_agent_id: str,
        run_id: str | None,
        run_revision: int,
    ) -> _ServiceToolCall:
        return _ServiceToolCall(
            name="agent",
            args={
                "action": "launch",
                "subagent_type": "Plan",
                "description": "plan leaf subtasks",
                "prompt": self._build_plan_worker_prompt(user_message),
                "run_in_background": False,
                "target_task_agent_type": self._parent_task_agent_type,
                "target_task_agent_id": parent_task_agent_id,
                "parent_task_agent_type": self._parent_task_agent_type,
                "parent_task_agent_id": parent_task_agent_id,
                "run_id": run_id,
                "run_revision": run_revision,
            },
        )

    def _build_plan_worker_prompt(self, user_message: str) -> str:
        target_language = llm_language_label()
        tool_guidance = self._tool_hint_resolver.render_guidance_block(
            self._resolve_planning_task_hint(
                user_message=user_message,
                request_profile="generic",
                default_leaf_type="CodeExplore",
            )
        )
        return (
            "Decompose the parent task into bounded leaf workers. "
            "Start from the most concrete likely anchor or owning code path, then split only by neighboring responsibilities that are actually needed. "
            "Prefer execution-ready subtasks around concrete modules, interfaces, or validation checks. "
            "Workers gather evidence; the parent task agent handles synthesis and the final answer. "
            "If the request mixes local workspace evidence with external or public evidence, split those into separate leaf workers instead of forcing everything into repo exploration. "
            "Do not create a final synthesis or compare-the-findings worker that depends on sibling outputs. "
            "Avoid generic subtasks that only gather context or summarize risks unless ambiguity remains unresolved. "
            "Return JSON with summary, findings, evidence, gaps, next_steps, and subtasks only. "
            f"Write all natural-language JSON values in {target_language} unless preserving exact names, paths, commands, or source titles. "
            f"Parent task: {user_message}" + (f"\n\n{tool_guidance}" if tool_guidance else "")
        )

    @staticmethod
    def _subtask_plan_from_plan_worker_result(result: Any) -> Optional[SubtaskPlan]:
        if not result.success or not isinstance(result.data, dict):
            return None
        payload = result.data.get("result")
        if not isinstance(payload, dict):
            return None
        subtasks = payload.get("subtasks")
        if not isinstance(subtasks, list) or not subtasks:
            return None
        return SubtaskPlan.from_dict(
            {
                "summary": str(payload.get("summary", "")).strip(),
                "subtasks": subtasks,
            }
        )

    def should_route_to_explore_task_agent(
        self, *, user_message: str, orchestration_plan: OrchestrationPlan
    ) -> bool:
        if orchestration_plan.mode != "decompose":
            return False
        if orchestration_plan.default_leaf_type != "CodeExplore":
            return False
        lowered = user_message.lower()
        return any(
            keyword in lowered
            for keyword in [
                "architecture",
                "codebase",
                "repo",
                "跨模块",
                "跨子系统",
                "代码架构",
                "项目架构",
                "代码库",
                "目录结构",
            ]
        )

    def _normalize_subtask_plan(
        self,
        *,
        user_message: str,
        raw_plan: SubtaskPlan,
        default_leaf_type: str,
        request_profile: str,
    ) -> SubtaskPlan:
        raw_subtasks = list(raw_plan.subtasks)
        if not raw_subtasks:
            raw_subtasks = self._fallback_subtask_plan(
                user_message,
                default_leaf_type,
                request_profile=request_profile,
            )
        normalized_subtasks: list[PlannedSubtask] = []
        for item in raw_subtasks:
            description = item.description
            subtask_prompt = item.prompt
            if self._is_synthesis_only_subtask(description, subtask_prompt):
                fields = (
                    {"description": description}
                    if full_content_logging_enabled()
                    else {"description_chars": len(description)}
                )
                logger.info(
                    "chat_planning.drop_synthesis_subtask",
                    request_profile=request_profile,
                    **fields,
                )
                continue
            subagent_type = self._normalize_leaf_subagent_type(
                requested_subagent_type=item.subagent_type,
                default_leaf_type=default_leaf_type,
                request_profile=request_profile,
                root_user_message=user_message,
                description=description,
                subtask_prompt=subtask_prompt,
            )
            normalized_subtasks.append(
                PlannedSubtask(
                    description=description,
                    subagent_type=subagent_type,
                    prompt=self._build_leaf_worker_prompt(
                        root_user_message=user_message,
                        subtask_description=description,
                        subtask_prompt=subtask_prompt,
                        request_profile=request_profile,
                        subagent_type=subagent_type,
                    ),
                    parallel_group=item.parallel_group,
                )
            )
        if not normalized_subtasks:
            normalized_subtasks = [
                PlannedSubtask(
                    description=item.description,
                    subagent_type=item.subagent_type,
                    prompt=self._build_leaf_worker_prompt(
                        root_user_message=user_message,
                        subtask_description=item.description,
                        subtask_prompt=item.prompt,
                        request_profile=request_profile,
                        subagent_type=item.subagent_type,
                    ),
                    parallel_group=item.parallel_group,
                )
                for item in self._fallback_subtask_plan(
                    user_message,
                    default_leaf_type,
                    request_profile=request_profile,
                )
            ]
        return SubtaskPlan(
            summary=raw_plan.summary,
            subtasks=normalized_subtasks,
        )

    def _parse_subtask_plan(self, response: str) -> Optional[SubtaskPlan]:
        raw = str(response or "").strip()
        if not raw:
            return None
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError:
            return None
        if not isinstance(payload, dict):
            return None
        subtasks = payload.get("subtasks")
        if not isinstance(subtasks, list) or not subtasks:
            return None
        normalized = SubtaskPlan.from_dict(payload)
        if not normalized.subtasks:
            return None
        return normalized


def _recent_planning_history(history: list[dict[str, Any]]) -> list[dict[str, str]]:
    return [
        {
            "role": str(item.get("role", "unknown")),
            "content": str(item.get("content", ""))[:400],
        }
        for item in history[-4:]
        if isinstance(item, dict) and str(item.get("content", "")).strip()
    ]


def _attach_workspace_context(
    planning_prompt: dict[str, Any],
    workspace_context: dict[str, str] | None,
) -> None:
    if workspace_context is not None:
        planning_prompt["workspace_context"] = workspace_context
