"""Shared embedding write pipeline for memory layers."""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field, replace
from typing import Any

from .chunking import ChunkedText
from .config_coordination import (
    get_embedding_execution_generation,
    get_embedding_publication_lock,
)
from .embedding_service import EmbeddingResult, MemoryEmbeddingService
from .sqlite_vec_index import EmbeddingRebuildIdentityChangedError, SqliteVecIndex

logger = logging.getLogger(__name__)


class EmbeddingPipelineIncompleteError(RuntimeError):
    """Raised when a strict rebuild cannot produce every requested vector."""


@dataclass(slots=True)
class EmbeddingPipelineItem:
    """One parent object and its chunk texts ready for vector upsert."""

    parent_id: str
    chunks: list[ChunkedText]
    metadata: dict[str, Any] = field(default_factory=dict)
    payload: Any = None


@dataclass(frozen=True, slots=True)
class _EmbeddingExecutionSnapshot:
    supported: bool
    generation: int
    profile_id: str | None = None
    dimension: int | None = None


def partition_embedding_pipeline_items(
    items: list[EmbeddingPipelineItem],
) -> tuple[list[EmbeddingPipelineItem], list[EmbeddingPipelineItem]]:
    """Split items with canonical text from items that cannot be embedded."""
    embeddable: list[EmbeddingPipelineItem] = []
    unembeddable: list[EmbeddingPipelineItem] = []
    for item in items:
        (embeddable if item.chunks else unembeddable).append(item)
    return embeddable, unembeddable


@dataclass(slots=True)
class EmbeddingPipelineResult:
    """Successful vector write result for one parent object."""

    parent_id: str
    chunks: list[ChunkedText]
    embeddings: list[EmbeddingResult]
    metadata: dict[str, Any]
    payload: Any
    embedded_at: float
    execution_snapshot: _EmbeddingExecutionSnapshot


@dataclass(slots=True)
class _EmbeddingWriteBatch:
    results: list[EmbeddingPipelineResult]
    vector_items: list[dict[str, Any]]


class MemoryEmbeddingPipeline:
    """Embed prepared chunk texts and persist them through one vector index."""

    def __init__(
        self,
        *,
        embedding_service: MemoryEmbeddingService,
        vector_index: SqliteVecIndex,
        text_builder_version: str | None = None,
    ) -> None:
        self._embedding_service = embedding_service
        self._vector_index = vector_index
        self._text_builder_version = text_builder_version

    async def upsert_items(
        self, items: list[EmbeddingPipelineItem]
    ) -> list[EmbeddingPipelineResult]:
        """Embed *items* and write all chunk vectors, with single-row fallback."""
        results = await self.prepare_items(items)
        return await self.persist_results(results)

    async def prepare_items(
        self,
        items: list[EmbeddingPipelineItem],
    ) -> list[EmbeddingPipelineResult]:
        """Compute embeddings without mutating the vector index."""
        prepared_items, _ = partition_embedding_pipeline_items(items)
        if not prepared_items:
            return []

        execution_snapshot = self._capture_execution_snapshot()
        texts = [chunk.text for item in prepared_items for chunk in item.chunks]
        embeddings = await self._embed_texts(texts)
        if not embeddings:
            if self._strict_rebuild_writes():
                raise EmbeddingPipelineIncompleteError(
                    "Embedding rebuild returned no vectors for prepared items"
                )
            return []
        if self._strict_rebuild_writes() and len(embeddings) != len(texts):
            raise EmbeddingPipelineIncompleteError(
                "Embedding rebuild returned a mismatched vector count"
            )
        if not self._execution_snapshot_is_current(execution_snapshot):
            if self._strict_rebuild_writes():
                raise EmbeddingRebuildIdentityChangedError(
                    "Embedding identity changed while vectors were being generated"
                )
            logger.info("Discarding memory embeddings generated by an inactive identity")
            return []
        results = self._build_successful_results(
            items=prepared_items,
            embeddings=embeddings,
            embedded_at=time.time(),
            execution_snapshot=execution_snapshot,
        )
        if self._strict_rebuild_writes() and len(results) != len(prepared_items):
            raise EmbeddingPipelineIncompleteError(
                "Embedding rebuild returned incomplete vectors for prepared items"
            )
        return results

    async def persist_results(
        self,
        results: list[EmbeddingPipelineResult],
    ) -> list[EmbeddingPipelineResult]:
        """Persist previously computed results through the vector index."""
        async with get_embedding_publication_lock():
            if not all(
                self._execution_snapshot_is_current(result.execution_snapshot) for result in results
            ):
                if self._strict_rebuild_writes():
                    raise EmbeddingRebuildIdentityChangedError(
                        "Embedding identity changed before vector publication"
                    )
                logger.info("Discarding prepared memory embeddings from an inactive identity")
                return []
            indexed_results = [
                replace(
                    result,
                    embeddings=[
                        self._result_for_index(embedding) for embedding in result.embeddings
                    ],
                )
                for result in results
            ]
            write_batch = _EmbeddingWriteBatch(
                results=indexed_results,
                vector_items=self._batch_vector_items(indexed_results),
            )
            if not write_batch.vector_items:
                return []
            return await self._persist_write_batch(write_batch)

    def _build_successful_results(
        self,
        *,
        items: list[EmbeddingPipelineItem],
        embeddings: list[EmbeddingResult | None],
        embedded_at: float,
        execution_snapshot: _EmbeddingExecutionSnapshot,
    ) -> list[EmbeddingPipelineResult]:
        results: list[EmbeddingPipelineResult] = []
        embedding_index = 0
        for item in items:
            chunk_embeddings = embeddings[embedding_index : embedding_index + len(item.chunks)]
            embedding_index += len(item.chunks)
            typed_embeddings = self._typed_chunk_embeddings(item, chunk_embeddings)
            if typed_embeddings is None:
                continue
            results.append(
                EmbeddingPipelineResult(
                    parent_id=item.parent_id,
                    chunks=item.chunks,
                    embeddings=typed_embeddings,
                    metadata=dict(item.metadata),
                    payload=item.payload,
                    embedded_at=embedded_at,
                    execution_snapshot=execution_snapshot,
                )
            )
        return results

    def _typed_chunk_embeddings(
        self,
        item: EmbeddingPipelineItem,
        chunk_embeddings: list[EmbeddingResult | None],
    ) -> list[EmbeddingResult] | None:
        if len(chunk_embeddings) != len(item.chunks):
            return None
        typed_embeddings: list[EmbeddingResult] = []
        for embedding in chunk_embeddings:
            if embedding is None:
                return None
            typed_embeddings.append(embedding)
        return typed_embeddings

    def _batch_vector_items(
        self,
        results: list[EmbeddingPipelineResult],
    ) -> list[dict[str, Any]]:
        vector_items: list[dict[str, Any]] = []
        for result in results:
            for chunk, embedding in zip(result.chunks, result.embeddings):
                metadata = dict(result.metadata)
                metadata.setdefault("chunk_index", chunk.chunk_index)
                vector_items.append(
                    {
                        "entity_id": self._vector_entity_id(result.parent_id, chunk),
                        "embedding": embedding,
                        "metadata": metadata,
                    }
                )
        return vector_items

    async def _persist_write_batch(
        self,
        write_batch: _EmbeddingWriteBatch,
    ) -> list[EmbeddingPipelineResult]:
        try:
            await self._vector_index.upsert_many(write_batch.vector_items)
            return write_batch.results
        except EmbeddingRebuildIdentityChangedError:
            raise
        except Exception as exc:
            if self._strict_rebuild_writes():
                raise
            logger.warning(
                "Failed batch upsert for memory embeddings, falling back to single-row writes: %s",
                exc,
            )
        return await self._fallback_upsert_results(write_batch.results)

    async def _fallback_upsert_results(
        self,
        results: list[EmbeddingPipelineResult],
    ) -> list[EmbeddingPipelineResult]:
        persisted_results: list[EmbeddingPipelineResult] = []
        for result in results:
            try:
                for vector_item in self._single_row_vector_items(result):
                    await self._vector_index.upsert(
                        entity_id=str(vector_item["entity_id"]),
                        embedding=vector_item["embedding"],
                        metadata=vector_item.get("metadata"),
                    )
                persisted_results.append(result)
            except EmbeddingRebuildIdentityChangedError:
                raise
            except Exception as item_exc:
                if self._strict_rebuild_writes():
                    raise
                logger.warning(
                    "Failed to upsert memory embedding chunks for %s: %s",
                    result.parent_id,
                    item_exc,
                )
        return persisted_results

    def _single_row_vector_items(
        self,
        result: EmbeddingPipelineResult,
    ) -> list[dict[str, Any]]:
        return [
            {
                "entity_id": self._vector_entity_id(result.parent_id, chunk),
                "embedding": embedding,
                "metadata": {**result.metadata, "chunk_index": chunk.chunk_index},
            }
            for chunk, embedding in zip(result.chunks, result.embeddings)
        ]

    async def _embed_texts(self, texts: list[str]) -> list[EmbeddingResult | None]:
        if hasattr(self._embedding_service, "embed_texts"):
            return await self._embedding_service.embed_texts(texts)
        return [await self._embedding_service.embed_text(text) for text in texts]

    def _result_for_index(self, embedding: EmbeddingResult) -> EmbeddingResult:
        if not self._text_builder_version:
            return embedding
        identity_builder = getattr(self._embedding_service, "result_for_index", None)
        if callable(identity_builder):
            return identity_builder(embedding, text_builder_version=self._text_builder_version)
        return embedding

    def _vector_entity_id(self, parent_id: str, chunk: ChunkedText) -> str:
        if chunk.chunk_id == parent_id or "::" in chunk.chunk_id:
            return chunk.chunk_id
        return f"{parent_id}::{chunk.chunk_id}"

    def _strict_rebuild_writes(self) -> bool:
        checker = getattr(self._vector_index, "in_rebuild_session", None)
        return bool(checker()) if callable(checker) else False

    def _capture_execution_snapshot(self) -> _EmbeddingExecutionSnapshot:
        generation = get_embedding_execution_generation()
        profile_getter = getattr(self._embedding_service, "get_active_profile", None)
        if not self._text_builder_version or not callable(profile_getter):
            return _EmbeddingExecutionSnapshot(supported=False, generation=generation)
        profile = profile_getter(text_builder_version=self._text_builder_version)
        if profile is None:
            return _EmbeddingExecutionSnapshot(supported=True, generation=generation)
        dimension = getattr(profile, "dimension", None)
        return _EmbeddingExecutionSnapshot(
            supported=True,
            generation=generation,
            profile_id=str(getattr(profile, "profile_id", "") or "") or None,
            dimension=int(dimension) if dimension is not None else None,
        )

    def _execution_snapshot_is_current(
        self,
        snapshot: _EmbeddingExecutionSnapshot,
    ) -> bool:
        if snapshot.generation != get_embedding_execution_generation():
            return False
        return not snapshot.supported or self._capture_execution_snapshot() == snapshot


def verify_active_rebuild_profile(
    *,
    embedding_service: Any,
    vector_index: Any,
    text_builder_version: str,
) -> None:
    """Compare the current service identity with the just-written rebuild."""

    profile_getter = getattr(embedding_service, "get_active_profile", None)
    identity_builder = getattr(embedding_service, "result_for_index", None)
    verifier = getattr(vector_index, "verify_rebuild_target", None)
    if not callable(profile_getter) or not callable(identity_builder) or not callable(verifier):
        return
    profile = profile_getter(text_builder_version=text_builder_version)
    if profile is None:
        verifier(model_key=None)
        return
    verifier(
        model_key=str(profile.profile_id),
        dimension=profile.dimension,
    )


__all__ = [
    "EmbeddingPipelineItem",
    "EmbeddingPipelineIncompleteError",
    "EmbeddingPipelineResult",
    "MemoryEmbeddingPipeline",
    "partition_embedding_pipeline_items",
    "verify_active_rebuild_profile",
]
