"""Planning helpers for ExploreTaskAgent."""
from __future__ import annotations

import json
from typing import Any, Optional

from ....core.logger import get_logger
from ..common import OrchestrationPlan
from .prompt_service import ExplorePromptService

logger = get_logger(__name__)


class ExplorePlanningService:
    """Owns canonical and model-planned Explore subtask generation."""

    def __init__(self, *, prompt_service: ExplorePromptService) -> None:
        self._prompt_service = prompt_service

    async def generate_subtask_plan(
        self,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan | dict[str, Any],
        user_id: str,
        session_id: str,
    ) -> dict[str, Any]:
        _ = (user_id, session_id)
        if isinstance(orchestration_plan, dict):
            orchestration_plan = OrchestrationPlan(
                mode=str(orchestration_plan.get("mode", "decompose") or "decompose"),
                planner=str(orchestration_plan.get("planner", "task_agent") or "task_agent"),
                default_leaf_type="Explore",
                allow_parallel=bool(orchestration_plan.get("allow_parallel", True)),
            )
        if self.is_repo_architecture_request(user_message):
            return {
                "summary": "Canonical codebase exploration plan.",
                "subtasks": self.canonical_repo_subtasks(user_message),
            }
        raw_plan = await self._plan_with_task_agent(user_message=user_message, history=history)
        if raw_plan is None:
            raw_plan = {
                "summary": "Fallback exploration plan generated by ExploreTaskAgent.",
                "subtasks": self.generic_fallback_subtasks(user_message),
            }
        return self.normalize_subtask_plan(user_message=user_message, raw_plan=raw_plan)

    async def _plan_with_task_agent(
        self,
        *,
        user_message: str,
        history: list[dict[str, Any]],
    ) -> Optional[dict[str, Any]]:
        planning_prompt = {
            "user_request": user_message,
            "recent_history": history[-4:],
            "requirements": [
                "Decompose the exploration request into bounded Explore leaf subtasks only.",
                "Keep each subtask narrow enough for one worker to finish independently.",
                "Prefer parallel subtasks whenever dependencies are weak.",
                "Do not include final user-facing prose.",
            ],
        }
        system_prompt = (
            "You are ExploreTaskAgent planning bounded Explore subtasks. "
            "Return ONLY valid JSON with this schema: "
            '{"summary":"string","subtasks":[{"description":"string","subagent_type":"Explore","prompt":"string","parallel_group":"string"}]}.'
        )
        try:
            response = await self._prompt_service.call_llm(
                system_prompt=system_prompt,
                messages=[{"role": "user", "content": json.dumps(planning_prompt, ensure_ascii=False)}],
                disable_thinking=False,
            )
        except Exception as exc:
            logger.warning("ExploreTaskAgent planning call failed | error=%s", exc)
            return None
        return self.parse_subtask_plan(response)

    def normalize_subtask_plan(self, *, user_message: str, raw_plan: dict[str, Any]) -> dict[str, Any]:
        raw_subtasks = raw_plan.get("subtasks")
        if not isinstance(raw_subtasks, list) or not raw_subtasks:
            raw_subtasks = self.generic_fallback_subtasks(user_message)
        normalized = []
        for item in raw_subtasks:
            if not isinstance(item, dict):
                continue
            description = str(item.get("description", "")).strip()
            prompt = str(item.get("prompt", "")).strip()
            if not description or not prompt:
                continue
            normalized.append(
                {
                    "description": description,
                    "subagent_type": "Explore",
                    "prompt": self.build_leaf_prompt(user_message, description, prompt),
                    "parallel_group": str(item.get("parallel_group", "default")).strip() or "default",
                }
            )
        return {
            "summary": str(raw_plan.get("summary", "")).strip(),
            "subtasks": normalized,
        }

    def parse_subtask_plan(self, response: str) -> Optional[dict[str, Any]]:
        raw = str(response or "").strip()
        if not raw:
            logger.warning("ExploreTaskAgent planning returned empty response")
            return None
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError:
            logger.warning("ExploreTaskAgent planning returned invalid JSON | response_preview=%s", raw[:300])
            return None
        if not isinstance(payload, dict):
            return None
        subtasks = payload.get("subtasks")
        if not isinstance(subtasks, list) or not subtasks:
            logger.warning("ExploreTaskAgent planning returned empty subtasks")
            return None
        return {
            "summary": str(payload.get("summary", "")).strip(),
            "subtasks": [
                {
                    "description": str(item.get("description", "")).strip(),
                    "subagent_type": "Explore",
                    "prompt": str(item.get("prompt", "")).strip(),
                    "parallel_group": str(item.get("parallel_group", "default")).strip() or "default",
                }
                for item in subtasks
                if isinstance(item, dict)
                and str(item.get("description", "")).strip()
                and str(item.get("prompt", "")).strip()
            ],
        }

    def canonical_repo_subtasks(self, user_message: str) -> list[dict[str, str]]:
        return [
            {
                "description": "Map repository layout",
                "subagent_type": "Explore",
                "prompt": self.build_leaf_prompt(
                    user_message,
                    "Map repository layout",
                    "Analyze the top-level directory structure, major modules, and entry folders.",
                ),
                "parallel_group": "group_a",
            },
            {
                "description": "Identify technology stack",
                "subagent_type": "Explore",
                "prompt": self.build_leaf_prompt(
                    user_message,
                    "Identify technology stack",
                    "Inspect dependency manifests and boot files to identify the backend, frontend, storage, and runtime stack.",
                ),
                "parallel_group": "group_a",
            },
            {
                "description": "Analyze frontend structure",
                "subagent_type": "Explore",
                "prompt": self.build_leaf_prompt(
                    user_message,
                    "Analyze frontend structure",
                    "Focus on frontend organization, bootstrap flow, routing, and the main UI entry points.",
                ),
                "parallel_group": "group_a",
            },
            {
                "description": "Analyze backend modules",
                "subagent_type": "Explore",
                "prompt": self.build_leaf_prompt(
                    user_message,
                    "Analyze backend modules",
                    "Focus on backend module boundaries, runtime startup, task agent chain, and the main execution flow.",
                ),
                "parallel_group": "group_a",
            },
            {
                "description": "Inspect project progress",
                "subagent_type": "Explore",
                "prompt": self.build_leaf_prompt(
                    user_message,
                    "Inspect project progress",
                    "Look for docs, progress trackers, release notes, or TODO-style files that indicate the current project status and recent progress.",
                ),
                "parallel_group": "group_a",
            },
        ]

    def generic_fallback_subtasks(self, user_message: str) -> list[dict[str, str]]:
        return [
            {
                "description": "Gather primary context",
                "subagent_type": "Explore",
                "prompt": self.build_leaf_prompt(
                    user_message,
                    "Gather primary context",
                    "Collect the most relevant files, modules, and source-of-truth evidence for the request.",
                ),
                "parallel_group": "group_a",
            },
            {
                "description": "Analyze implementation details",
                "subagent_type": "Explore",
                "prompt": self.build_leaf_prompt(
                    user_message,
                    "Analyze implementation details",
                    "Inspect the core implementation path, dependencies, and behavior that matter for the request.",
                ),
                "parallel_group": "group_a",
            },
            {
                "description": "Summarize risks and gaps",
                "subagent_type": "Explore",
                "prompt": self.build_leaf_prompt(
                    user_message,
                    "Summarize risks and gaps",
                    "Identify open questions, gaps, and next actions needed to complete the request.",
                ),
                "parallel_group": "group_b",
            },
        ]

    def build_leaf_prompt(self, root_user_message: str, subtask_description: str, subtask_prompt: str) -> str:
        return "\n".join(
            [
                f"Parent user request: {root_user_message}",
                f"Assigned exploration subtask: {subtask_description}",
                "Task-specific instructions:",
                subtask_prompt,
                "Success criteria:",
                "- Stay strictly within this subtask scope.",
                "- Use absolute file paths in findings and evidence when you reference code.",
                "- Keep the result bounded and evidence-driven.",
                "- If the scope cannot be completed, set result_status to failed and explain the failure_reason.",
            ]
        )

    def is_repo_architecture_request(self, user_message: str) -> bool:
        lowered = user_message.lower()
        return any(
            keyword in lowered
            for keyword in ["architecture", "codebase", "repo", "代码架构", "项目架构", "代码库", "目录结构"]
        )
