"""Planning helpers for ExploreTaskAgent."""
from __future__ import annotations

import json
from typing import Any, Optional

from ....utils.diagnostic_logging import full_content_logging_enabled
from ....core.logger import get_logger
from ....tools.registry import tool_registry
from ....tools.tool_hint_resolver import ToolHintResolver
from ...orchestration import PlannedSubtask, SubtaskPlan
from ..common import OrchestrationPlan
from .prompt_service import ExplorePromptService

logger = get_logger(__name__)

STRUCTURED_PLANNING_TIMEOUT_SECONDS = 180.0


class ExplorePlanningService:
    """Owns LLM-first and fallback Explore subtask generation."""

    _EXPLORE_TOOL_HINT_CANDIDATES = ["glob", "grep", "file_read"]

    def __init__(self, *, prompt_service: ExplorePromptService, tool_hint_resolver: ToolHintResolver | None = None) -> None:
        self._prompt_service = prompt_service
        self._tool_hint_resolver = tool_hint_resolver or ToolHintResolver(tool_registry)

    async def generate_subtask_plan(
        self,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan,
        user_id: str,
        session_id: str,
        run_id: str | None = None,
        run_revision: int = 0,
        workspace_root: str | None = None,
    ) -> SubtaskPlan:
        _ = (user_id, session_id, run_id, run_revision, workspace_root)
        raw_plan = await self._plan_with_task_agent(
            user_message=user_message,
            history=history,
            orchestration_plan=orchestration_plan,
        )
        if raw_plan is None:
            raw_plan = SubtaskPlan(
                summary="Fallback exploration plan generated by ExploreTaskAgent.",
                subtasks=self.fallback_subtasks_for_request(user_message),
            )
        return self.normalize_subtask_plan(user_message=user_message, raw_plan=raw_plan)

    async def _plan_with_task_agent(
        self,
        *,
        user_message: str,
        history: list[dict[str, Any]],
        orchestration_plan: OrchestrationPlan,
    ) -> Optional[SubtaskPlan]:
        recent_history = [
            {
                "role": str(item.get("role", "unknown")),
                "content": str(item.get("content", ""))[:400],
            }
            for item in history[-4:]
            if isinstance(item, dict) and str(item.get("content", "")).strip()
        ]
        seed_subtasks = self.seed_subtasks_for_request(user_message)
        task_hint = self._resolve_task_hint(user_message)
        planning_prompt = {
            "user_request": user_message,
            "recent_history": recent_history,
            "allow_parallel": orchestration_plan.allow_parallel,
            "scope_hints": self.describe_request_scope(user_message),
            "task_hints": task_hint,
            "seed_subtasks": [item.to_dict() for item in seed_subtasks],
            "requirements": [
                "Decompose the exploration request into bounded CodeExplore leaf subtasks only.",
                "Keep each subtask narrow enough for one worker to finish independently.",
                "Prefer parallel subtasks whenever dependencies are weak.",
                "Start from the most concrete likely anchor or owning code path, then split by neighboring responsibilities only when needed.",
                "Use the seed subtasks as a starting point, but adapt them to the user's actual scope.",
                "If the user is asking about only one subsystem, folder, or path, keep the plan inside that scope.",
                "Prefer execution-ready subtasks that end in validated findings from current source files.",
                "Avoid generic research-only subtasks like 'gather context' or 'summarize risks' unless the request explicitly needs them or ambiguity remains unresolved.",
                "You may remove irrelevant seed subtasks, rewrite them, or add at most two necessary subtasks.",
                "Return between 2 and 6 subtasks unless the request is truly tiny.",
                "Do not include final user-facing prose.",
            ],
        }
        system_prompt = (
            "You are ExploreTaskAgent planning bounded CodeExplore subtasks. "
            "Return ONLY valid JSON with this schema: "
            '{"summary":"string","subtasks":[{"description":"string","subagent_type":"CodeExplore","prompt":"string","parallel_group":"string"}]}. '
            "Do not answer the user directly. Produce execution-ready CodeExplore leaf tasks only. "
            "Prefer subtasks organized around concrete entry points, owning modules, and validating evidence from current files. "
            "When task_hints are present, use them to keep the first search pass efficient and bounded."
        )
        try:
            response = await self._prompt_service.call_llm(
                system_prompt=system_prompt,
                messages=[{"role": "user", "content": json.dumps(planning_prompt, ensure_ascii=False)}],
                disable_thinking=False,
                json_mode=True,
                timeout_seconds=STRUCTURED_PLANNING_TIMEOUT_SECONDS,
            )
        except Exception as exc:
            logger.warning("ExploreTaskAgent planning call failed | error=%s", exc)
            return None
        return self.parse_subtask_plan(response)

    def normalize_subtask_plan(self, *, user_message: str, raw_plan: SubtaskPlan) -> SubtaskPlan:
        raw_subtasks = list(raw_plan.subtasks)
        if not raw_subtasks:
            raw_subtasks = self.fallback_subtasks_for_request(user_message)
        normalized: list[PlannedSubtask] = []
        seen_descriptions: set[str] = set()
        for item in raw_subtasks:
            description = str(item.description).strip()
            prompt = str(item.prompt).strip()
            if not description or not prompt:
                continue
            dedupe_key = description.lower()
            if dedupe_key in seen_descriptions:
                continue
            seen_descriptions.add(dedupe_key)
            normalized.append(
                PlannedSubtask(
                    description=description,
                    subagent_type="CodeExplore",
                    prompt=self.build_leaf_prompt(user_message, description, prompt),
                    parallel_group=str(item.parallel_group or "default").strip() or "default",
                )
            )
            if len(normalized) >= 6:
                break
        if len(normalized) < 2:
            normalized = [
                PlannedSubtask(
                    description=item.description,
                    subagent_type="CodeExplore",
                    prompt=self.build_leaf_prompt(user_message, item.description, item.prompt),
                    parallel_group=item.parallel_group,
                )
                for item in self.fallback_subtasks_for_request(user_message)
            ]
        return SubtaskPlan(summary=raw_plan.summary, subtasks=normalized)

    def parse_subtask_plan(self, response: str) -> Optional[SubtaskPlan]:
        raw = str(response or "").strip()
        if not raw:
            logger.warning("ExploreTaskAgent planning returned empty response")
            return None
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError:
            if full_content_logging_enabled():
                logger.warning(
                    "ExploreTaskAgent planning returned invalid JSON | response_preview=%s",
                    raw[:300],
                )
            else:
                logger.warning(
                    "ExploreTaskAgent planning returned invalid JSON | response_chars=%d",
                    len(raw),
                )
            return None
        if not isinstance(payload, dict):
            return None
        subtasks = payload.get("subtasks")
        if not isinstance(subtasks, list) or not subtasks:
            logger.warning("ExploreTaskAgent planning returned empty subtasks")
            return None
        normalized = SubtaskPlan.from_dict(payload)
        return normalized if normalized.subtasks else None

    def canonical_repo_subtasks(self, user_message: str) -> list[PlannedSubtask]:
        return [
            PlannedSubtask(
                description="Map repository layout",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Map repository layout",
                    "Analyze the top-level directory structure, major modules, and entry folders.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Identify technology stack",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Identify technology stack",
                    "Inspect dependency manifests and boot files to identify the backend, frontend, storage, and runtime stack.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Analyze frontend structure",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Analyze frontend structure",
                    "Focus on frontend organization, bootstrap flow, routing, and the main UI entry points.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Analyze backend modules",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Analyze backend modules",
                    "Focus on backend module boundaries, runtime startup, task agent chain, and the main execution flow.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Inspect project progress",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Inspect project progress",
                    "Look for docs, progress trackers, release notes, or TODO-style files that indicate the current project status and recent progress.",
                ),
                parallel_group="group_a",
            ),
        ]

    def scoped_backend_subtasks(self, user_message: str) -> list[PlannedSubtask]:
        return [
            PlannedSubtask(
                description="Map backend scope",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Map backend scope",
                    "Identify the relevant backend directories, entry files, and major module boundaries inside the requested backend scope.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Trace backend execution flow",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Trace backend execution flow",
                    "Trace the main backend startup, request handling, or task execution flow that matters for this scope.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Summarize backend gaps",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Summarize backend gaps",
                    "Identify missing context, unclear dependencies, and follow-up reads needed to complete the backend analysis.",
                ),
                parallel_group="group_b",
            ),
        ]

    def scoped_frontend_subtasks(self, user_message: str) -> list[PlannedSubtask]:
        return [
            PlannedSubtask(
                description="Map frontend scope",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Map frontend scope",
                    "Identify the relevant frontend directories, app shell, and major feature boundaries inside the requested scope.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Trace frontend bootstrap and routing",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Trace frontend bootstrap and routing",
                    "Trace how the frontend initializes, routes, and reaches the main UI flow within the requested scope.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Summarize frontend gaps",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Summarize frontend gaps",
                    "Identify unclear ownership boundaries, state flow questions, and follow-up reads needed for the frontend scope.",
                ),
                parallel_group="group_b",
            ),
        ]

    def path_scoped_subtasks(self, user_message: str) -> list[PlannedSubtask]:
        return [
            PlannedSubtask(
                description="Map requested scope",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Map requested scope",
                    "Map the requested directory or module scope, including the closest entry files, manifests, and ownership boundaries.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Inspect scope implementation",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Inspect scope implementation",
                    "Inspect the main implementation path, dependencies, and source-of-truth files inside the requested scope.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Summarize scope risks and gaps",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Summarize scope risks and gaps",
                    "Identify open questions, risks, and the next follow-up reads needed inside the requested scope.",
                ),
                parallel_group="group_b",
            ),
        ]

    def seed_subtasks_for_request(self, user_message: str) -> list[PlannedSubtask]:
        if self.is_repo_architecture_request(user_message):
            return self.canonical_repo_subtasks(user_message)
        lowered = user_message.lower()
        if any(keyword in lowered for keyword in ["backend", "后端", "server", "api", "runtime"]):
            return self.scoped_backend_subtasks(user_message)
        if any(keyword in lowered for keyword in ["frontend", "前端", "ui", "页面", "router", "react"]):
            return self.scoped_frontend_subtasks(user_message)
        if self.is_path_scoped_request(user_message):
            return self.path_scoped_subtasks(user_message)
        return self.generic_fallback_subtasks(user_message)

    def fallback_subtasks_for_request(self, user_message: str) -> list[PlannedSubtask]:
        if self.is_repo_architecture_request(user_message):
            return self.canonical_repo_subtasks(user_message)
        return self.seed_subtasks_for_request(user_message)

    def generic_fallback_subtasks(self, user_message: str) -> list[PlannedSubtask]:
        return [
            PlannedSubtask(
                description="Locate the primary anchor",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Locate the primary anchor",
                    "Find the smallest set of files, symbols, or entry modules most likely to control the requested behavior or answer.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Trace the owning implementation path",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Trace the owning implementation path",
                    "Follow the code path that directly computes, routes, or controls the requested behavior, pulling in only the nearby dependencies needed to explain it.",
                ),
                parallel_group="group_a",
            ),
            PlannedSubtask(
                description="Validate gaps and edge cases",
                subagent_type="CodeExplore",
                prompt=self.build_leaf_prompt(
                    user_message,
                    "Validate gaps and edge cases",
                    "Validate important edge cases, unresolved assumptions, and remaining gaps from source evidence instead of repeating broad summary prose.",
                ),
                parallel_group="group_b",
            ),
        ]

    def build_leaf_prompt(self, root_user_message: str, subtask_description: str, subtask_prompt: str) -> str:
        tool_guidance = self._tool_hint_resolver.render_guidance_block(
            self._resolve_task_hint(root_user_message),
        )
        return "\n".join(
            [
                f"Parent user request: {root_user_message}",
                f"Assigned exploration subtask: {subtask_description}",
                "Task-specific instructions:",
                subtask_prompt,
                *( [tool_guidance] if tool_guidance else [] ),
                "Success criteria:",
                "- Stay strictly within this subtask scope.",
                "- Start from the most concrete anchor available: an entry file, symbol, path, or directly controlling module.",
                "- If you name a file, symbol, route, config key, or flag, verify it exists in the current code before relying on it.",
                "- Prefer focused glob/grep/read steps over broad repository scans.",
                "- Use absolute file paths in findings and evidence when you reference code.",
                "- Keep the result bounded and evidence-driven.",
                "- If the scope cannot be completed, set result_status to failed and explain the failure_reason.",
            ]
        )

    def _resolve_task_hint(self, user_message: str) -> dict[str, Any]:
        return self._tool_hint_resolver.resolve(
            user_message=user_message,
            available_tools=list(self._EXPLORE_TOOL_HINT_CANDIDATES),
            scope_hints=self.describe_request_scope(user_message),
        )

    def describe_request_scope(self, user_message: str) -> list[str]:
        lowered = user_message.lower()
        hints: list[str] = []
        if self.is_repo_architecture_request(user_message):
            hints.append("The request asks for a repository- or architecture-level exploration.")
        if self.is_path_scoped_request(user_message):
            hints.append("The request references an explicit path or subdirectory. Keep subtasks inside that scope unless a dependency forces expansion.")
        if any(keyword in lowered for keyword in ["backend", "后端", "server", "api", "runtime"]):
            hints.append("The request appears backend-focused.")
        if any(keyword in lowered for keyword in ["frontend", "前端", "ui", "页面", "router", "react"]):
            hints.append("The request appears frontend-focused.")
        if any(keyword in lowered for keyword in ["memory", "记忆", "agent", "worker", "task_agent", "task agent"]):
            hints.append("The request may target an internal subsystem rather than the whole repository.")
        if not hints:
            hints.append("No strong scope hint is available. Infer the smallest useful exploration scope from the request wording.")
        return hints

    def is_path_scoped_request(self, user_message: str) -> bool:
        return any(
            marker in user_message
            for marker in ["~/", "/", "\\", "src/", "backend/", "frontend/", "docs/", "scripts/"]
        )

    def is_repo_architecture_request(self, user_message: str) -> bool:
        lowered = user_message.lower()
        return any(
            keyword in lowered
            for keyword in ["architecture", "codebase", "repo", "代码架构", "项目架构", "代码库", "目录结构"]
        )
