"""
Contracts for five-layer agent architecture.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Optional
import time
import uuid

from .types import LayerTaskType, StubCapability


@dataclass
class LayerContext:
    """Canonical context carried across layers."""

    user_id: str
    message: str
    session_id: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))


@dataclass
class RouteDecision:
    """Decision generated by router layer."""

    task_type: LayerTaskType
    intent: str = "chat"
    reasoning: str = ""
    need_user_intervention: bool = False
    stub_capability: Optional[StubCapability] = None


@dataclass
class TaskEnvelope:
    """Task payload shared by task/worker/action layers."""

    task_id: str
    context: LayerContext
    decision: RouteDecision
    payload: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LayerResult:
    """Unified execution result used by all layers."""

    success: bool
    payload: Dict[str, Any] = field(default_factory=dict)
    error: Optional[str] = None
    need_user_intervention: bool = False
    deferred: bool = False
    stub_capability: Optional[StubCapability] = None
