"""Shared chat trace event constants."""

FACT_EVENTS_TABLE = "fact_events"
RUNTIME_OBSERVATIONS_TABLE = FACT_EVENTS_TABLE
USER_EVENT_TYPES = ("UserMessage",)
AI_RESPONSE_EVENT_TYPES = ("AIResponse",)
FACT_DISPLAY_EVENT_TYPES = USER_EVENT_TYPES + AI_RESPONSE_EVENT_TYPES
LEGACY_TRACE_EVENT_TYPES = ("TOOL_INTERACTION", "TOOL_INVOKED", "CHAT_TOOL_LOOP_STEP")
TURN_TRACE_EVENT_TYPES = ("TURN_TRACE_STARTED", "TURN_TRACE_COMPLETED", "TURN_TRACE_FAILED")
TRACE_NODE_EVENT_TYPES = ("TRACE_NODE_STARTED", "TRACE_NODE_COMPLETED", "TRACE_NODE_FAILED")
TRACE_EVENT_TYPES = LEGACY_TRACE_EVENT_TYPES + TURN_TRACE_EVENT_TYPES + TRACE_NODE_EVENT_TYPES
MAX_PLAN_PREVIEW_STEPS = 3


__all__ = [
    "AI_RESPONSE_EVENT_TYPES",
    "FACT_DISPLAY_EVENT_TYPES",
    "FACT_EVENTS_TABLE",
    "LEGACY_TRACE_EVENT_TYPES",
    "MAX_PLAN_PREVIEW_STEPS",
    "RUNTIME_OBSERVATIONS_TABLE",
    "TRACE_EVENT_TYPES",
    "TRACE_NODE_EVENT_TYPES",
    "TURN_TRACE_EVENT_TYPES",
    "USER_EVENT_TYPES",
]
